build.gradle, config/build.gradle, config/src/main/java/com/oing/ServerApplication.java, config/src/main/resources/application.yaml, config/src/test/java/com/oing/ServerApplicationTests.java, member/build.gradle, member/src/main/java/com/oing/controller/MemberController.java, member/src/main/java/com/oing/service/MemberService.java, settings.gradle
---
모듈 간 의존성을 최소화하고 유지보수 용이성을 향상시키기 위해 멀티모듈을 도입했습니다.
---
- 멀티모듈 도입: config 모듈과 member 모듈 추가
- root project의 build.gradle: 모든 하위 프로젝트(subprojects)에 대한 공통 설정을 정의
- config 모듈의 build.gradle: member 모듈에 대한 의존성을 추가하고, Spring Boot 및 기타 라이브러리에 대한 의존성을 정의
- member 모듈의 build.gradle 
- 테스트를 위한 `test` API 생성
---
- 멀티 모듈 처음 도입해봤는데 수정해야 할 부분에 대해 코멘트 남겨주시면 바로 수정하겠습니다.
- 테스트를 위해 `test` API를 만들었는데 해당 PR에 문제가 없다면 merge 전에 `test` API는 삭제하겠습니다.
---
=> chore: configure multi-module project structure

.github/workflows/build.yaml, .github/workflows/deploy.yaml, .github/workflows/prod.yaml, config/build.gradle
---
CI/CD 구축 (https://no5ing.atlassian.net/browse/OING-5) 을 위함
---
CI (빌드) 파이프라인을 추가하였습니다.
---
안녕하세요 반갑습니다
---
https://no5ing.atlassian.net/browse/OING-7
=> [OING-7] chore: CI 파이프라인 추가

build.gradle
---
#7 이 `dev`로 머지가 되면서 `config` 모듈이 Jacoco 테스트 커버리지 기준을 충족하지 못하여 테스트가 실패합니다. `config` 모듈을 테스트 범위에서 제외하는 것이 적절하다고 생각하여 해당 PR을 올립니다.
---
- Jacoco 테스트 범위에서 `config` 모듈 제외
---
추가적으로 커버리지 범위에서 제거해야 할 모듈이나 파일이 있다면 알려주세요.
---
https://no5ing.atlassian.net/browse/OING-23
=> [OING-23] chore: Jacoco 테스트 커버리지 범위에서 config 모듈 제외

config/src/main/java/com/oing/config/SpringWebConfig.java, config/src/main/java/com/oing/config/SwaggerConfig.java, config/src/main/java/com/oing/config/filter/WebRequestInterceptor.java, config/src/main/resources/application.yaml
---
프론트 측에서 백엔드 API를 UI 상에서 편리하게 이용할 수 있도록 Swagger를 세팅했습니다.
---
- Swagger 세팅
- 인터셉터 url pattern에서 swagger관련 제외하도록 추가
---
http://localhost:8080/swagger-ui/index.html 로 접속하면 Authentication failed가 뜹니다. `SpringWebConfig`의 인터셉터 적용 범위에서 스웨거 관련 패턴들을 다 제거하도록 추가했지만 해결되지 않습니다. 현재 상황에서는 해결할 수 없는 문제라 생각해서 PR을 올렸는데 해결할 수 있는 문제라면 알려주세요.
---
https://no5ing.atlassian.net/browse/OING-24
=> [OING-24] chore: Swagger 환경 세팅

.github/workflows/deploy.yaml, .github/workflows/dev.yaml, .github/workflows/prod.yaml, .github/workflows/test.yaml, build.gradle, config/build.gradle
---
슬랙 알림 및 테스트 커버리지 측정이 필요했습니다.
---
- dev,master,release 브랜치로 PR시 테스트 커비리지 및 테스트를 실행토록 하였습니다
- dev,master 배포시 슬랙에 알림을 보내도록 설정하였습니다
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-26
=> [OING-26] chore: CI/CD 파이프라인 워크플로우 개선

member/src/test/java/com/oing/domain/model/MemberTest.java, member/src/test/java/com/oing/domain/model/SocialMemberTest.java, post/build.gradle, post/src/main/java/com/oing/domain/model/MemberPost.java, post/src/main/java/com/oing/domain/model/MemberPostComment.java, post/src/main/java/com/oing/domain/model/MemberPostReaction.java, post/src/main/java/com/oing/repository/MemberPostCommentRepository.java, post/src/main/java/com/oing/repository/MemberPostReactionRepository.java, post/src/main/java/com/oing/repository/MemberPostRepository.java, post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java, post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java, post/src/test/java/com/oing/domain/model/MemberPostTest.java
---
MemberPost 도메인 DDL 기반 모델을 구성했습니다.
---
- MemberPost 엔티티 및 레포지토리 구성
- MemberPostComment 엔티티 및 레포지토리 구성
- MemberPostReaction 엔티티 및 레포지토리 구성
- 새로 생성한 도메인에 대해 테스트 코드 추가
---
수정해야 할 부분이 있는지 확인해주세요. 🥲
---
https://no5ing.atlassian.net/browse/OING-58
=> [OING-58] feat: MemberPost 도메인 entity & repository 구성

common/src/main/java/com/oing/util/PreSignedUrlGenerator.java, gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java, gateway/src/main/resources/db/migration/V2__modify_Post.sql, gateway/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java, member/src/test/java/com/oing/domain/CreateNewUserDTOTest.java, post/src/main/java/com/oing/controller/PostController.java, post/src/main/java/com/oing/controller/PostReactionController.java, post/src/main/java/com/oing/domain/model/MemberPost.java, post/src/main/java/com/oing/domain/model/MemberPostReaction.java, post/src/main/java/com/oing/dto/request/CreatePostRequest.java, post/src/main/java/com/oing/dto/response/PostResponse.java, post/src/main/java/com/oing/restapi/PostApi.java, post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java, post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java, post/src/test/java/com/oing/domain/model/MemberPostTest.java, post/src/test/java/com/oing/dto/response/PostFeedResponseTest.java
---
피드 업로드 API 모킹 및 피드 업로드를 위한 presigned-url 요청 로직을 리팩터링했습니다.
---
- Post 도메인 ddl 및 엔티티 수정
- `content` 컬럼 추가
- `imageUrl` 컬럼 not null 설정 추가
- Post reaction 도메인 ddl 및 엔티티 수정
- `ascii` 필드명을 `emoji`로 수정 (이모지 로직이 고정 5개 이모지만 사용할 수 있게 바뀌어서 필드명도 수정했습니다)
- 피드 업로드 API 모킹
- 피드 업로드를 위한 presigned-url 요청 로직 리팩터링
- 경로 수정: `/images/{memberId}` =>  `/images/feed`
---
추가적으로 수정해야할 부분이 있는지 확인해주세요. 🙂
=> [OING-67] feat: 피드 업로드 API 모킹

member/src/main/java/com/oing/controller/MemberController.java
---
순찬님과 상의했을 때 당분간 프로필 및 피드 이미지 주소를 풀 url로 저장하는 것이 맞다고 생각하여 풀 url이 아닌 path를 기준으로 이미지 삭제하는 로직을 주석처리 했습니다.
---
- 회원 프로필 이미지 수정 기능에서 기존 이미지 삭제 로직 주석처리
---
리뷰 잘부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-98
=> [OING-98] feat: 회원 프로필 이미지 수정 기능에서 기존 이미지 삭제 로직 주석처리

common/src/main/java/com/oing/domain/model/BaseAuditEntityWithDelete.java, common/src/main/java/com/oing/domain/model/DeletableBaseAuditEntity.java, common/src/main/java/com/oing/exception/AuthorizationFailedException.java, member/src/main/java/com/oing/controller/MemberController.java, member/src/main/java/com/oing/domain/model/Member.java, member/src/main/java/com/oing/repository/SocialMemberRepository.java, member/src/main/java/com/oing/restapi/MemberApi.java, member/src/main/java/com/oing/service/MemberService.java, member/src/test/java/com/oing/domain/SocialLoginProviderTest.java
---
회원 탈퇴 API를 구현했습니다.
---
- BaseAuditEntityWithDelete 구현
- 회원 탈퇴 API 구현
- Member와 연결된 모든 SocialMember 객체 삭제
- 회원 정보 마스킹 
---
SocialMember를 다 끊어내면 된다고 하셔서 이렇게 구현했습니다. 로직이 맞는지 확인해주세요. 🎄메리크리스마스 🎄
---
https://no5ing.atlassian.net/browse/OING-92
=> [OING-92] feat: 회원 탈퇴 API 구현

gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
---
새로운 형태의 Object storage url으로 인해 썸네일 url이 작동하지 못한 오류 해결했습니다.
---
- bucketImageUrl에서 imagePath를 찾는 코드의 패턴을 변경
---
요청받은 오류 해결했습니다.
---
https://no5ing.atlassian.net/browse/OING-111
=> [OING-111] 새로운 형태의 Object storage url으로 인해 썸네일 url이 작동하지 못한 오류 해결

gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
---
#65 처럼 새로운 형태의 Object storage url에서 이미지 키를 제대로 추출되지 않는 버그를 확인하여 로직을 수정했습니다.
---
- 두가지 형태의 url에서 이미지 키를 추출하도록 로직 수정
---
추가적으로 대응해야 할 부분이 있는지 확인해주세요
---
https://no5ing.atlassian.net/browse/OING-123
=> [OING-123] hotfix: 새로운 형태의 Object storage url으로 인해 이미지 키가 제대로 추출되지 않는 오류 해결 

gateway/src/test/resources/application.yaml, member/src/main/java/com/oing/repository/MemberRepository.java, member/src/main/java/com/oing/service/MemberService.java, member/src/test/java/com/oing/domain/SocialLoginProviderTest.java
---
가족 멤버 프로필 조회 시, 탈퇴한 회원은 응답에 포함되지 않도록 수정했습니다.
---
- 가족 멤버 프로필 조회 시, 탈퇴한 회원은 제외되도록 수정
- SocialLoginProvider 테스트 에러 해결
---
리뷰 잘 부탁드려요~~
---
https://no5ing.atlassian.net/browse/OING-128
=> [OING-128] refactor: 가족 멤버 프로필 조회 시, 탈퇴한 회원은 응답에서 제외되도록 수정

gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java, gateway/src/main/resources/db/migration/V202401082259__delete_postDate_column.sql, member/src/main/java/com/oing/exception/FamilyNotFoundException.java, member/src/main/java/com/oing/service/MemberService.java, post/src/main/java/com/oing/controller/MemberPostController.java, post/src/main/java/com/oing/domain/MemberPost.java, post/src/main/java/com/oing/repository/MemberPostRepository.java, post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java, post/src/main/java/com/oing/service/MemberPostService.java, post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java, post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java, post/src/test/java/com/oing/domain/model/MemberPostTest.java
---
Post에서 postDate 컬럼 삭제 및 가족이 없는 멤버에 대해 가족 프로필 조회 시, 예외 반환 로직 추가했습니다.
---
- postDate 컬럼 삭제
- 가족이 없는 멤버에 대해 가족 프로필 조회 시, 예외 반환 로직 추가
---
확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-130
=> [OING-130] feat: postDate 컬럼 삭제 및 가족이 없는 멤버에 대해 가족 프로필 조회 시, 예외 반환 로직 추가

gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java, gateway/src/main/java/com/oing/controller/WidgetController.java, gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java
---
프로필 사진이 없는 유저의 경우 이름을 통해 디폴트 프로필을 클라이언트에서 만들기 위해, 응갑 객체에 작성자 이름을 추가해달라고 요청받았슴다.
---
- SingleRecentPostWidgetResponse에 authorName 추가, profileImageUrl -> authorProfileImageUrl 변경
---

---
https://no5ing.atlassian.net/browse/OING-131
=> [OING-131] 위젯 응답 객체에 게시자 이름 추가

gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
---
이미지를 압축하는 빈에서 이미지가 없어 Null일 때, NullPointerException이 발생하는 것을 발견했습니다.
---
- bucketImageUrl이 NULL이면 압축하지 않고, 그대로 NULL을 반환하도록 코드 추가
---
파이팅
---
https://no5ing.atlassian.net/browse/OING-129
=> [OING-129] 이미지 최적화 빈의 NullPointerException 방지

member/src/main/java/com/oing/controller/MemberController.java, member/src/main/java/com/oing/domain/CreateNewUserDTO.java, member/src/main/java/com/oing/dto/request/UpdateMemberNameRequest.java
---
QA 중 디자인 팀의 요청으로 닉네임 길이 제한을 `2자~10자` -> `1자~9자`로 수정했습니다.
---
- 닉네임 길이 제한 수정
---
수정해야할 곳이 더 있는지 확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-135
=> [OING-135] hotfix: 닉네임 길이 제한 조건 수정

post/src/main/java/com/oing/controller/MemberPostController.java, post/src/main/java/com/oing/repository/MemberPostCommentRepository.java, post/src/main/java/com/oing/repository/MemberPostReactionRepository.java, post/src/main/java/com/oing/restapi/MemberPostApi.java, post/src/main/java/com/oing/service/MemberPostCommentService.java, post/src/main/java/com/oing/service/MemberPostReactionService.java, post/src/main/java/com/oing/service/MemberPostService.java, post/src/main/java/com/oing/service/event/DeleteMemberPostEvent.java
---
프론트의 요청으로 테스트를 위한 피드 삭제 기능을 추가했습니다.
---
피드 삭제 api 추가
---
- 테스트용 api 여서 본인이 작성한 글인지 확인하는 검증 로직은 다 제거했습니다.
- 같은 패키지 안에 있더라도 서비스에서 다른 레포 의존성을 갖는 것보단 이벤트 리스너로 풀어내는 게 좋다고 생각해서 위와 같이 구현했는데 괜찮은지 확인해주세요. (지금처럼 이벤트리스너 써서 한 서비스 안에 하나의 레포만 참조하는 게 좋을지 or 한 서비스 안에 여러 레포 참조하는 게 좋을지)
---
https://no5ing.atlassian.net/browse/OING-148
=> [OING-148] feat: Post 삭제 기능 추가

gateway/src/main/resources/db/migration/V202401141930__add_real_emoji_tbl.sql, post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java, post/src/main/java/com/oing/controller/MemberRealEmojiController.java, post/src/main/java/com/oing/domain/MemberPost.java, post/src/main/java/com/oing/domain/MemberPostRealEmoji.java, post/src/main/java/com/oing/domain/MemberRealEmoji.java, post/src/main/java/com/oing/dto/request/CreateMyRealEmojiRequest.java, post/src/main/java/com/oing/dto/request/PostRealEmojiRequest.java, post/src/main/java/com/oing/dto/response/MyPostRealEmojisResponse.java, post/src/main/java/com/oing/dto/response/PostRealEmojiResponse.java, post/src/main/java/com/oing/dto/response/RealEmojiResponse.java, post/src/main/java/com/oing/dto/response/RealEmojisResponse.java, post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java, post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java, post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java, post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java, post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java, post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java, post/src/test/java/com/oing/domain/model/MemberPostTest.java
---
리얼 이모지 기능이 추가되면서 필요한 테이블 클래스와 기본 api 틀을 작성했습니다.
---
- 리얼 이모지 테이블 migration 파일 추가
- 리얼 이모지 테이블 클래스 추가
- 사용자가 생성한 리얼 이모지 테이블 클래스
- 피드에 남긴 리얼 이모지 테이블 클래스 
- 리얼 이모지에 필요한 기본적인 API 틀 추가
---
리얼 이모지 api uri를 계층적으로 나누어야 할 지 고민을 하다가 사용자가 자신의 리얼 이모지를 생성하기 위한 API 클래스는 포스트 패키지 아래에 있지만 실제로는 post 객체와는 상관없으므로 uri에서는 /posts 경로를 제외했습니다. 괜찮은지 확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-147
=> [OING-147] feat: 리얼 이모지 테이블 클래스 및 리얼 이모지 API 틀 추가

common/src/test/java/com/oing/QueryDslTestConfig.java, gateway/src/main/java/com/oing/controller/CalendarController.java, gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java, gateway/src/main/java/com/oing/restapi/CalendarApi.java, gateway/src/main/resources/application-test.yaml, gateway/src/test/java/com/oing/controller/CalendarControllerTest.java, gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java, gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
---
캘린더 API와 관련된 모든 코드에 테스트 코드를 작성했습니다.
---
- CalendarApiTest 통합 테스트 추가 (restapi interface는 jacoco 커버리지에서 관측안됨)
- CalendarControllerTest 단위 테스트 추가
- MemberPostRepositoryCustom에서 캘린더에서 사용하는 메소드에 DataJpaTest 추가
---
파이팅
---
https://no5ing.atlassian.net/browse/OING-105
=> [OING-105] feat: 캘린더 API를 위한 테스트 추가

common/src/main/java/com/oing/exception/StringEmptyWhiteSpaceException.java, gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
---
이미지 url 중에 null이 아닌 빈 문자열이 디비에 저장된 경우가 있었고, 이로인해 OptimizedImageProvider가 런타임 예외를 발생시키고 있었음.
---
- StringEmptyWhiteSpaceException 추가
- OptimizedImageProvider에서 url이 null or 빈 문자열인 경우 null을 반환하도록 예외 처리
- OptimizedImageProvider에서 url이 비정상적인 패턴인 경우, 압축하지 않고 그대로 반환하도록 예외 처리
---
핫픽스 머지 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-156
=> [OING-156] refactor: 이미지의 예상되지 않은 url 패턴으로 인한 OptimizedImageProvider의 런타임 예외를 방지

gateway/src/test/java/com/oing/restapi/MemberRealEmojiApiTest.java, post/src/main/java/com/oing/controller/MemberRealEmojiController.java, post/src/main/java/com/oing/dto/response/RealEmojiResponse.java, post/src/main/java/com/oing/dto/response/RealEmojisResponse.java, post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java, post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java, post/src/main/java/com/oing/service/MemberRealEmojiService.java, post/src/test/java/com/oing/controller/MemberPostCommentControllerTest.java, post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
---
회원의 리얼이모지 조회 API mock을 했어야 했는데 모르고 구현을 해버렸습니다...
---
- 회원의 리얼이모지 조회 API 구현
- 회원의 리얼이모지 조회 단위테스트 코드 작성
- 회원의 리얼이모지 조회 인수테스트 코드 작성
- 코멘트 단위테스트 코드 에러 수정
---
현재 브랜치에서 캘린더 단위테스트 하나가 깨지는 거 참고해주세요~
---
https://no5ing.atlassian.net/browse/OING-154
=> [OING-154] feat: 회원의 리얼이모지 조회 API 구현

gateway/src/test/java/com/oing/restapi/MemberPostReactionApiTest.java, post/src/main/java/com/oing/controller/MemberPostReactionController.java, post/src/main/java/com/oing/dto/request/PostReactionRequest.java, post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java
---
피드 리액션 중, 제가 맡은 등록/삭제/남긴 멤버 조회 기능에 대해 테스트 코드 작성했습니다.
---
- 리액션 등록/삭제/남긴 멤버 조회 기능 단위 테스트코드 작성
- 리액션 등록/삭제/남긴 멤버 조회 기능 통합 테스트코드 작성
---
리뷰 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-161
=> [OING-161] test: 피드 리액션 등록/삭제/남긴 멤버 조회 기능 테스트 코드 작성

post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java, post/src/main/java/com/oing/dto/response/PostRealEmojiResponse.java
---
피드에 등록된 리얼이모지 리스트를 조회하는 API를 모킹했습니다.
---
- 피드에 등록된 리얼이모지 리스트 조회 API 모킹
---
응답 필드에 추가적으로 들어가야 하는 필드가 있는지 확인해주시면 감사합니다!
현재 브랜치에서 캘린더 단위테스트 하나가 깨지는 거 참고해주세요~
---
https://no5ing.atlassian.net/browse/OING-159
=> [OING-159] feat: 피드에 등록된 리얼이모지 리스트 조회 API 모킹

gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java, post/src/main/java/com/oing/controller/MemberPostReactionController.java, post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java, post/src/main/java/com/oing/dto/response/PostReactionMemberResponse.java, post/src/main/java/com/oing/dto/response/PostRealEmojiMemberResponse.java, post/src/main/java/com/oing/dto/response/PostRealEmojiSummaryResponse.java, post/src/main/java/com/oing/restapi/MemberPostReactionApi.java, post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java, post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java, post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
---
피드 리얼이모지 요약/리스트/멤버 조회 API를 구현했습니다.
---
- 피드 리얼이모지 요약/리스트/멤버 조회 API 구현
- 해당 PR에서 구현한 기능에 대해 단위 테스트 코드 작성
- 해당 PR에서 구현한 기능에 대해 인수 테스트 코드 작성
---
해당 PR에서 구현한 기능들 모두 repository를 접근해서 데이터를 가져오는 로직이 아니어서 단위 테스트 코드의 경우 호출했을 때 예외가 나지 않는지 정도만 체크했습니다.
---
https://no5ing.atlassian.net/browse/OING-158
=> [OING-158] feat: 피드 리얼이모지 조회 API 구현

gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java, gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java, post/src/main/java/com/oing/controller/MemberPostController.java, post/src/test/java/com/oing/controller/MemberPostControllerTest.java
---
post 도메인 중 PresignedUrl 발급과 게시글 등록/삭제 기능에 대해 테스트 코드를 추가했습니다.
---
- Post PresignedUrl/DELETE 단위 테스트 코드 추가
- Post PresignedUrl/POST/DELETE 통합 테스트 코드 추가
- `existsByMemberIdAndCreatedAt` 레포지토리 테스트 코드 추가
---
게시글 등록에 대해 단위 테스트를 실행하려면 post 객체의 `createdAt`을 테스트 코드 내에서 설정해야 하는데 저희 프로젝트에서는 `@EnableJpaAuditing`로 처리를 하고 있어 테스트 코드를 작성하기 어렵네요. 좋은 아이디어 있다면 알려주세요~
---
https://no5ing.atlassian.net/browse/OING-162
=> [OING-162] test: Post PresignedUrl/POST/DELETE 테스트 코드 추가

gateway/src/main/java/com/oing/controller/CalendarController.java, gateway/src/main/java/com/oing/dto/response/BannerResponse.java, gateway/src/main/java/com/oing/restapi/CalendarApi.java, gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
---
추억캘린더의 2차 MVP 기능에 해당하는 새로운 배너를 위한 API입니다.
---
- getBanner API in CalendarApi 추가
- getBanner request in CalendarController 모킹
- getBanner 기본 조회를 위한 통합테스트 추가
---
늦어서 죄송..
---
https://no5ing.atlassian.net/browse/OING-165
=> [OING-165] feat: 추억캘린더 새 배너 API 설계 및 모킹

post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java, post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java, post/src/main/java/com/oing/service/MemberPostRealEmojiService.java, post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
---
기존의 포스트 리얼 이모지 삭제 로직에서는 memberId와 realEmojiId로만 postRealEmoji를 찾으려 했습니다. 그렇기에 다른 게시글에도 같은 리얼 이모지를 남긴 경우 서버에서는 어떤 postRealEmoji를 삭제해야 할지 모르기 때문에 500 에러가 반환됐습니다. postId도 추가해서 함께 찾도록 하여 해결했습니다.
---
- 포스트에 달린 리얼이모지 삭제 로직 버그 해결
---
리뷰 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-171
=> [OING-171] hotfix: 포스트에 달린 리얼이모지 삭제 로직 버그 해결

gateway/src/test/java/com/oing/restapi/CalendarApiTest.java, member/src/main/java/com/oing/domain/Member.java, member/src/main/java/com/oing/service/MemberService.java
---
회원가입 시, 프로필 이미지 값이 있다면 이미지 키 값도 함께 저장하도록 로직을 추가했습니다.
---
- 회원가입 시, 프로필 이미지 키 추출해서 저장하도록 로직 수정
---
이 부분 말고도 이미지 키 추출해서 저장해야 하는 곳이 있다면 알려주세요~
---
https://no5ing.atlassian.net/browse/OING-172
=> [OING-172] hotfix: 회원가입 시, profileImgUrl이 있다면 이미지 키 추출해서 저장하도록 로직 수정

gateway/src/main/resources/application-test.yaml, gateway/src/test/java/com/oing/controller/WidgetControllerTest.java, gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
---
계속 미뤄지던 Widget API 코드 들에 대한 테스트 코드를 추가했습니다. Repository 비즈니스 로직은 Calendar와 같은 로직을 사용하고 있어 이전에 추가한  #104 #81 에서 이미 반영되었습니다.
---
- WidgetController에 대한 단위 테스트 추가
- WidgetApi에 대한 통합 테스트 추가
---
파이팅 ㅠ
---
https://no5ing.atlassian.net/browse/OING-105
=> [OING-105] test: Widget API 테스트 코드 추가

gateway/src/main/java/com/oing/controller/WidgetController.java
---
#128 PR에서 생성자 파라미터 사용 실수로 발생한 버그 수정
---
파라미터가 잘못 사용된 SingleRecentPostWidgetResponse 생성자를 고침
---
---
https://no5ing.atlassian.net/browse/OING-179
=> [OING-179] fix: 파라미터가 잘못 사용된 SingleRecentPostWidgetResponse 생성자를 고침

gateway/src/main/java/com/oing/restapi/CalendarApi.java, post/src/main/java/com/oing/restapi/MemberPostApi.java
---
스프링 내에서 자동 주입되어 프론트에서 보낼 필요가 없는 familyId 파라미터를 스웨거에서 숨김처리했습니다.
---
- 자동 주입되는 familyId 파라미터 숨김 처리
---
리뷰 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-182
=> [OING-182] refactor: 자동 주입되는 familyId 파라미터 숨김 처리

gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
---
썸네일 에러 원인이 오타 같아서 수정했습니다.
---
썸에일 쿼리 스트링 수정
---
main으로 머지되면 레디스 서버에 있는 캐시값들 다 지워주세요.
---
https://no5ing.atlassian.net/browse/OING-189
=> [OING-189] hotfix: THUMBNAIL_OPTIMIZER_QUERY_STRING 오타 수정

gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java, gateway/src/main/resources/db/migration/V202402061321__add_familyId_column.sql, gateway/src/test/java/com/oing/controller/CalendarControllerTest.java, gateway/src/test/java/com/oing/controller/WidgetControllerTest.java, gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java, gateway/src/test/java/com/oing/restapi/CalendarApiTest.java, gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java, gateway/src/test/java/com/oing/restapi/MemberPostCommentApiTest.java, gateway/src/test/java/com/oing/restapi/MemberPostReactionApiTest.java, gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java, gateway/src/test/java/com/oing/restapi/WidgetApiTest.java, post/src/main/java/com/oing/controller/MemberPostController.java, post/src/main/java/com/oing/domain/MemberPost.java, post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java, post/src/main/java/com/oing/service/MemberPostService.java, post/src/test/java/com/oing/controller/MemberPostCommentControllerTest.java, post/src/test/java/com/oing/controller/MemberPostControllerTest.java, post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java, post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java, post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java, post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java, post/src/test/java/com/oing/domain/model/MemberPostTest.java, post/src/test/java/com/oing/service/MemberPostCommentServiceTest.java
---
게시물 생성/조회에서 그룹을 탈퇴한 회원 대응 가능하도록 로직 수정하였습니다.
---
- 포스트 도메인에 familyId 컬럼 추가
- 게시물 생성에서 그룹을 탈퇴한 회원 대응 가능하도록 로직 수정
- 탈퇴한 그룹에서 오늘 날짜에 포스트를 작성했어도 새 그룹에서 오늘 날짜에 포스트 작성 가능하도록 수정
- 게시물 조회에서 그룹을 탈퇴한 회원 대응 가능하도록 로직 수정
- 그룹을 탈퇴한 회원의 글들은 탈퇴한 그룹에서만 보이도록 로직 수정
---
로직이 바뀜에 따라 테스트코드가 자잘하게 수정되었는데 옳게 수정되었는지 확인해주세요~ 테스트들은 다 통과됩니다.
---
https://no5ing.atlassian.net/browse/OING-192
=> [OING-192] hotfix: 게시물 생성/조회에서 그룹을 탈퇴한 회원 대응 가능하도록 로직 수정

gateway/src/main/resources/db/migration/V202402071837__add_familyId_column_to_MemberRealEmoji.sql, gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java, gateway/src/test/java/com/oing/restapi/MemberRealEmojiApiTest.java, member/src/main/java/com/oing/domain/Member.java, post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java, post/src/main/java/com/oing/controller/MemberRealEmojiController.java, post/src/main/java/com/oing/domain/MemberRealEmoji.java, post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java, post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java, post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java, post/src/main/java/com/oing/service/MemberRealEmojiService.java, post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java, post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
---
회원이 그룹 탈퇴를 했을 때를 대비하여, 회원 리얼이모지 테이블에 familyId를 추가하고 로직을 수정했습니다.
---
- 회원리얼이모지 familyId 컬럼 추가
- 회원리얼이모지 로직 수정
- 회원리얼이모지 생성/조회/수정 시, 회원의 familyId를 이용해 처리
- 수정된 로직에 따라 테스트코드 수정
---
로컬에서 API 호출하면서 회원의 가족이 바뀌어도 적절히 대응함을 확인했는데 리얼이모지 안에서 추가적으로 familyId를 고려해야 하는 기능이 있다면 알려주세요
---
https://no5ing.atlassian.net/browse/OING-193
=> [OING-193] feat: 회원 리얼이모지 familyId 컬럼 추가 및 로직 수정

gateway/src/test/java/com/oing/restapi/MemberApiTest.java, member/src/main/java/com/oing/controller/MemberController.java, member/src/main/java/com/oing/domain/Member.java, member/src/main/java/com/oing/restapi/MemberApi.java, member/src/test/java/com/oing/controller/MemberControllerTest.java
---
프론트의 요청으로 회원 프로필 이미지 삭제 API를 추가했습니다.
---
- 회원 프로필 이미지 삭제 API 구현
- 회원 프로필 이미지 삭제 테스트코드 추가
---
프로필 이미지 삭제 로직 안에서 해당 회원의 프로필 이미지가 설정되어 있는지 검증하는 로직은 필요없다 생각하여 뺐는데 필요하다면 알려주세요~
---
https://no5ing.atlassian.net/browse/OING-194
=> [OING-194] feat: 회원 프로필 이미지 삭제 API 구현

gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java, gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java, post/src/main/java/com/oing/repository/MemberPostReactionRepository.java, post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java, post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java, post/src/main/java/com/oing/service/MemberPostReactionService.java
---
한 사람당 하나만 등록되어야 하는 post 메서드 api에 우선적으로 비관적 락을 적용했습니다.
---
- 비관적 락 적용
- 게시글 등록 api
- 회원 리얼이모지 등록 api
- 게시글 리액션 등록 api
- 게시글 리얼이모지 등록 api 
---
테스트코드는 이후에 올리겠습니다. 비관적 락이 올바른 곳에 적용됐는지 확인부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-200
=> [OING-200] hotfix: 동시성 이슈를 해결하기 위해 비관적 락 적용

build.gradle
---
자코코 테스트 커버리지 적용 범위를 수정했습니다.
---
- 자코코 테스트 커버리지 적용 범위 수정
- restapi, controller, repository 를 제외하고 현재 테스트가 적용되고 있는 디렉터리 제외
---
일단 임의로 이렇게 적용 범위를 수정했는데 추가/제외하고 싶은 적용 범위가 있다면 얘기해주세요. 오늘 회의때 잠깐 얘기 나눠도 좋을 거 같아요.
---
https://no5ing.atlassian.net/browse/OING-199
=> [OING-199] chore: 자코코 테스트 커버리지 적용 범위 수정

gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
---
캘린더 화면에서 가족 전체 추억 수가 불일치하는 이슈
---
memberPost의 familyId를 통해 쿼리하도록 변경
---
감사합니다
=> [OING-224] hotfix: 가족 통계 전체 추억 수 불일치 이슈

build.gradle, common/src/main/java/com/oing/service/FamilyScoreBridge.java, common/src/main/java/com/oing/util/DateUtils.java, family/src/main/java/com/oing/domain/CreateNewFamilyTopPercentageHistoryDTO.java, family/src/main/java/com/oing/domain/FamilyTopPercentageHistory.java, family/src/main/java/com/oing/domain/FamilyTopPercentageHistoryId.java, family/src/main/java/com/oing/job/FamilyStatisticJob.java, family/src/main/java/com/oing/service/FamilyService.java, family/src/main/java/com/oing/service/FamilyTopPercentageHistoryService.java, gateway/src/main/java/com/oing/ServerApplication.java, gateway/src/main/java/com/oing/config/ScheduleConfig.java, gateway/src/main/java/com/oing/service/FamilyScoreBridgeImpl.java, gateway/src/main/resources/db/migration/V202402252319__alter_FamolyTopPercentageHistory_tbl.sql, gateway/src/main/resources/db/migration/V202402260000__add_ShedLock_tbl.sql
---
감사히도 피드백주신 #158 를 드디어 도입하게 되었습니다. ShedLock을 통해 락을 추가하였고, 인스턴스 간의 중복이 발생하지 않도록 스케줄의 최소 lock 소유 시간을 30초로 잡았습니다. (어차피 한달에 한 번 실행하므로)
수정하는 김에 관련 코드와 테이블을 클린하게 변경했습니다.
---
- FamilyTopPercentageHistory 테이블 구조 변경
- 테이블의 기존 데이터이 정상적으로 작동하도록 default 값을 추가하여 flyway 작성
- ShedLock 도입
- recordAllFamilyTopPercentageHistoriesMonthly 스케줄에 락 추가 (최소, 최대 30초 Locked)
- 로깅 추가
---
ShedLock 공식 가이드를 따라 flyway도 추가하였지만, 간혹 ShedLock 테이블이 정상적으로 연결되지 않는 경우도 있다고 들었습니다. dev 환경에서 제대로 실행되는지 확인할 필요가 있습니다.
---
https://no5ing.atlassian.net/browse/OING-206
=> [OING-206] feat: 가족 이력 데이터 테이블 및 코드를 클린하게 리팩토링하고 ShedLock 도입

.github/workflows/build.yaml, .github/workflows/dev.yaml, .github/workflows/prod.yaml, build.gradle, family/src/main/java/com/oing/job/FamilyStatisticJob.java, gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java, gateway/src/main/java/com/oing/job/DailyNotificationJob.java, gateway/src/main/resources/application.yaml
---
라이브 서버에서 추적되지 않고있는 401, 400 UNKNOWN exception error를 추적하기 위해, 서버의 예외와 메시지를 추적 및 관리해주는 Sentry를 도입했습니다. 다만 NCP monitor 서버에 구축하였으나, 구동을 위해 굉장한 사양을 요구하는 것으로 보입니다. (NCP monitor 서버 Scale-up 함: 2 vCPU 8GB Ram -> 4 vCPU 16GB RAM) 도입이후 유지비 대비 유용성을 계속 검토해야할 것으로 보입니다.
Sentry에 필요한 라이브러리 도커를 구동중인 모습
---
- Sentry 구축 및 스프링 부트와 연결
- `SpringWebExceptionHandler`에서 모든 예외 추적 추가
- `FamilyStatisticJob`와 `DailyNotificationJob`의 스케줄링 잡에 메시지 추적 추가
---
원래 정책은 개발서버가 아닌 라이브 서버에만 Sentry가 적용되어야 하지만. Sentry에 멀티 모듈 프로젝트 적용 가이드도 없고 첫 도입이라 우선 개발 서버에 Sentry를 적용하여 테스트해볼 예정입니다. **정상작동이 확인되면 빠르게 라이브 서버에 적용하여 데이터를 수집하고 싶으므로, 금일 27(화) 중으로 개발서버에서 테스트 및 버전 릴리즈와 Sentry 적용을 했으면 합니다.**
---
https://no5ing.atlassian.net/browse/OING-208
=> [OING-208] feat: Sentry 도입 및 예외와 스케줄링 Job 추적 추가

post/src/main/java/com/oing/controller/MemberPostCommentController.java, post/src/main/java/com/oing/controller/MemberPostController.java, post/src/main/java/com/oing/controller/MemberPostReactionController.java, post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java, post/src/main/java/com/oing/controller/MemberRealEmojiController.java, post/src/main/java/com/oing/restapi/MemberPostApi.java, post/src/test/java/com/oing/controller/MemberPostControllerTest.java, post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
---
post 모듈 기능에 대해 로깅을 추가했습니다.
---
- 포스트 컨트롤러 로깅 추가
- 회원 리얼이모지 컨트롤러 로깅 추가
- 포스트 리얼이모지 컨트롤러 로깅 추가
- 포스트 코멘트 컨트롤러 로깅 추가
- 포스트 리액션 컨트롤러 로깅 추가
---
오타가 있거나 보완할 부분이 있다면 알려주세요~
그리고 리얼이모지/리액션을 등록/삭제 할 때 해당 회원이 이미 등록/삭제했는지 확인하는 검증 로직이 있는데 이 부분은 프론트에서 사용자가 이모지 한번 더 눌렀을 때 등록/삭제 어느 operation을 취해야할지 확인하는 용도로도 쓰인다고 생각해서 로깅을 안했는데 이 방법이 맞을까요? (이거까지 로깅하면 많은 로그가 쌓일 거 같아 로깅에서 제외했습니다)
---
https://no5ing.atlassian.net/browse/OING-250
=> [OING-250] feat: post 모듈 로깅 추가

member/src/main/java/com/oing/domain/Member.java, member/src/test/java/com/oing/controller/MemberControllerTest.java
---
회원 탈퇴 시, 프로필 이미지 키를 삭제 기능이 없어 추가했습니다.
---
- 회원 탈퇴 시, 프로필 이미지 키 삭제 기능 추가
---
확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-270
=> [OING-270] feat: 회원 탈퇴 시, 프로필 이미지 키 삭제 기능 추가

family/src/main/java/com/oing/job/FamilyStatisticJob.java
---
월간 가족 이력 데이터 기록 스케줄러를 UTC 기준으로 설정되어 있었습니다.
---
- UTC로 설정된 월간 가족 이력 데이터 기록 스케줄러를 KST로 변경
---
ㅎ;
=> fix: UTC로 설정된 월간 가족 이력 데이터 기록 스케줄러를 KST로 변경

common/src/main/java/com/oing/exception/ErrorCode.java, gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java, gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java, gateway/src/main/resources/application-dev.yaml, gateway/src/main/resources/application-prod.yaml, member/src/main/java/com/oing/exception/TokenExpiredException.java, member/src/main/java/com/oing/exception/TokenNotValidException.java
---
센트리 체크 중에 일부 잘못된 설정으로 인해 스택 트레이스가 안될 여지가 있어서 급하게 고쳤고, 이와 함께 향상시킬 부분이 보여서 진행했습니다.
---
- minimum-breadcrumb-level를 DEBUG로 변경
- InvalidTokenExcpetion 핸들링에서 공통적으로 핸들링 하던 ExpiredJwtTokenException을 분리
- Authentication failed 에러 코드를 공통적으로 사용하고 있던 것을 Token Authentication Failed와 Token Expired로 세분화
---
minimum-breadcrumb-level 는 스택 트레이스에 관련된 세팅이므로, 캡쳐하는 예외 레밸과는 다릅니다.
---
https://no5ing.atlassian.net/browse/OING-252
=> [OING-252] refactor: 잘못된 Sentry 로깅 설정 수정 및 Jwt Token 예외 핸들링 일부 리펙토링

gateway/src/main/java/com/oing/config/RedisConfig.java, gateway/src/test/java/com/oing/restapi/CalendarApiTest.java, gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java, gateway/src/test/java/com/oing/support/EmbeddedRedisConfig.java, gateway/src/test/java/com/oing/support/RedisTestConfig.java
---
서버 이전을 하면서 레디스가 serverless(cluster mode)로 바뀌어 레디스 설정 파일에서는 클러스터 모드인데 임베디드 레디스는 단일 구성 설정이라 제대로 동작되지 않았습니다. 
클러스터 모드이지만 port를 하나만 쓰는 단일 구성형태라 임베디드 레디스는 그대로 두고 임베디드 레디스를 위한 테스트용 RedisConfig 파일을 생성했습니다.
---
- test용 RedisConfig 추가
---
임베디드 레디스가 실행되어 캘린더쪽 테스트코드가 돌아가는지 확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-277
=> [OING-277] fix: test용 RedisConfig 추가

build.gradle, common/src/main/java/com/oing/event/MemberPostCommentCreatedEvent.java, common/src/main/java/com/oing/event/MemberPostCommentDeletedEvent.java, common/src/main/java/com/oing/event/MemberPostCreatedEvent.java, common/src/main/java/com/oing/event/MemberPostDeletedEvent.java, common/src/main/java/com/oing/event/MemberPostReactionCreatedEvent.java, common/src/main/java/com/oing/event/MemberPostReactionDeletedEvent.java, common/src/main/java/com/oing/event/MemberPostRealEmojiCreatedEvent.java, common/src/main/java/com/oing/event/MemberPostRealEmojiDeletedEvent.java, family/src/main/java/com/oing/event/FamilyScoreEventListener.java, family/src/main/java/com/oing/repository/FamilyRepositoryCustom.java, family/src/main/java/com/oing/repository/FamilyRepositoryCustomImpl.java, family/src/main/java/com/oing/service/FamilyService.java, gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java, post/src/main/java/com/oing/domain/MemberPostCommentEntityListener.java, post/src/main/java/com/oing/domain/MemberPostEntityListener.java, post/src/main/java/com/oing/domain/MemberPostReactionEntityListener.java, post/src/main/java/com/oing/domain/MemberPostRealEmojiEntityListener.java
---
#200 에서 점수가 정상적으로 산정되지 않던 크리티컬 이슈는 해결되었지만, 여전히 게시글 작성과 댓글 작성 등 메인 비즈니스 로직과 트랜잭션이 분리되어 있지 않았습니다. 이러한 강결합 구조를 해결하였습니다. 또한 Thread.sleep으로 스마트하지 못하게 이벤트를 테스트하고 있는 구조를 외부 라이브러리로 해결했습니다
---
- 가족 점수 산정용 이벤트를 비동기로 전환
- 비동기로 인해 데드락이 발생하는 것을 해결하기 위해, getFamilyByFamilyId 메소드에 비관적 락 도입
- Awaitility 라이브러리를 통해 이벤트 검증을 위한 통합 테스트를 더 깔끔하게 구현
- 이벤트와 관련된 전체 로직에 더 자세한 로깅을 추가
---
이런저런 이슈로 해결하는데 오래 걸려서 수정사항이 좀 많네용..
---
https://no5ing.atlassian.net/browse/OING-284
=> [OING-284] refactor: 가족 활동 점수 이벤트의 강결합 및 데드락 해결과 비동기용 테스트코드 도입

gateway/src/test/java/com/oing/event/DatabaseCleaner.java
---
테스트 실행 중 FamilyScoreEventListnerTest가 실패하는 문제를 파악하고 해결했습니다.
---
- FamilyScoreEventListnerTest의 DatabaseCleaner 익스텐션이 flyway db는 truncate하지 않도록 예외 추가
---
큰 변경점없이 픽스한거니 빠르게 부탁드려요!
---
https://no5ing.atlassian.net/browse/OING-288
=> [OING-288] fix: 테스트 중 FamilyScoreEventListnerTest가 실패하는 문제 해결

member/src/main/java/com/oing/repository/MemberRepository.java, member/src/main/java/com/oing/service/MemberService.java
---
캘린더 API에서 모든 가족 업로드 여부의 계산 로직에서 삭제한 유저도 구성원에 포함하고 있는 결함을 발견하여, 수정하는 PR입니다.
---
- 가족구성원 조회에서 삭제된 유저는 제외하도록 쿼리 수정
- 사용안되고 있는 방치된 메소드 삭제
---
간단하게 픽스한 사안이라 빠르게 부탁쓰
---
https://no5ing.atlassian.net/browse/OING-291
=> [OING-291] fix: 캘린더 API의 가족구성원 계산 로직이 삭제한 유저도 포함하는 결함을 수정

gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java, gateway/src/test/java/com/oing/controller/CalendarControllerTest.java, gateway/src/test/java/com/oing/controller/WidgetControllerTest.java, gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java, gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java, gateway/src/test/java/com/oing/restapi/CalendarApiTest.java, gateway/src/test/java/com/oing/restapi/CommentApiTest.java, gateway/src/test/java/com/oing/restapi/PostApiTest.java, gateway/src/test/java/com/oing/restapi/ReactionApiTest.java, gateway/src/test/java/com/oing/restapi/RealEmojiApiTest.java, gateway/src/test/java/com/oing/restapi/WidgetApiTest.java, post/src/main/java/com/oing/controller/PostController.java, post/src/main/java/com/oing/domain/Post.java, post/src/main/java/com/oing/domain/PostType.java, post/src/main/java/com/oing/domain/Type.java, post/src/main/java/com/oing/dto/response/PostResponse.java, post/src/main/java/com/oing/repository/PostRepositoryCustom.java, post/src/main/java/com/oing/restapi/PostApi.java, post/src/main/java/com/oing/service/PostService.java, post/src/test/java/com/oing/controller/PostCommentControllerTest.java, post/src/test/java/com/oing/controller/ReactionControllerTest.java, post/src/test/java/com/oing/controller/RealEmojiControllerTest.java, post/src/test/java/com/oing/domain/model/PostCommentTest.java, post/src/test/java/com/oing/domain/model/PostReactionTest.java, post/src/test/java/com/oing/domain/model/PostTest.java, post/src/test/java/com/oing/dto/response/PostFeedResponseTest.java, post/src/test/java/com/oing/service/CommentServiceTest.java, post/src/test/java/com/oing/service/ReactionServiceTest.java, post/src/test/java/com/oing/service/RealEmojiServiceTest.java
---
미션 포스트 작성/조회 모킹 API 추가했습니다.
---
- 미션 포스트 작성/조회 모킹 API 추가
---
**바뀐 파일이 많습니다. 커밋 별로 봐주세요!**
- 빠른 모킹을 위해 미션 작성/조회에서 별도로 검증 로직 추가하는 부분은 제외했는데 프론트에서 원한다면 추가하겠습니다.
- 기존 포스트 작성/조회 API에 param을 추가해서 미션 포스트도 처리 가능하도록 설계했습니다. 더 좋은 의견이 있다면 알려주세요~
(param이 없거나 feed -> feed post / mission -> mission post)
- 🚨 포스트 조회의 경우, QueryDSL로 페이지네이션을 처리하고 있는데 임의적으로 응답을 모킹하기가 힘들어 일단 **?type=mission 으로 조회해도 기존에 있던 feed type의 포스트가 조회**되도록 했습니다. 만약 지금 로직을 크게 바꾸지 않는 선에서 임의로 응답 모킹이 가능하다면 방법 알려주신다면 그렇게 바꾸겠습니다!
---
https://no5ing.atlassian.net/browse/OING-302
=> [OING-302] feature: 미션 포스트 작성/조회 모킹 API 추가

post/src/main/java/com/oing/service/PostService.java
---
생존신고 업로드 가능 시간 정책이 변경되어 오전 10시부터 허용하도록 수정했습니다.
---
- 생존신고 업로드 가능 시간 변경
---
확인 부탁드려요~~
---
https://no5ing.atlassian.net/browse/OING-303
=> [OING-303] feature: 생존신고 업로드 가능 시간 변경

gateway/src/main/resources/db/migration/V202404152221__create_Mission_module_tables.sql
---
PR #230 이 머지되면서 발생한 "미션 모듈 엔티티들의 테이블 추가 flyway db.migration 중 발생한 에러"를 해결하기 위해서 올립니다.
---
- flyway db.migration sql 파일에 백틱(`)이 아니라 작은 따옴표(')를 사용한 부분들을 수정
---
확인 부탁드려요!
---
https://no5ing.atlassian.net/browse/OING-312
=> [OING-312] fix: OING-307 티켓의 미션 모듈 엔티티들의 테이블 추가 flyway db.migration 중 발생한 에러 해결

gateway/src/main/java/com/oing/controller/HomeController.java, gateway/src/main/java/com/oing/dto/response/FamilyMemberMonthlyRankingResponse.java, gateway/src/main/java/com/oing/dto/response/FamilyMemberRankerResponse.java, gateway/src/main/java/com/oing/restapi/HomeApi.java
---
가족구성원 랭킹 API를 프론트에게 우선적으로 요청받았기 때문에, API Mocking을 진행하였습니다.
---
- HomeAPI, HomeController 추가
- getFamilyMemberMonthlyRanking API spec 구현
- getFamilyMemberMonthlyRanking API controller 모킹
---
@CChuYong 요청한 사안압니다. 그리고 생성한 HomeAPI에 회의에서 언급된 홈화면 상단 프로필 API를 마이그레이션하면 될 것 같습니다.
---
https://no5ing.atlassian.net/browse/OING-308
=> [OING-308] feat: 가족구성원 랭킹 API 모킹

gateway/src/main/resources/db/migration/V202404171338__set_type_column_default_value_in_Post.sql
---
기존 post의 데이터들이 type값이 FEED로 저장되어 있는 이슈가 생겨 SURVIVAL로 다시 바꾸는 sql문을 추가했습니다.
---
- 기존 post의 데이터들이 type값이 FEED로 저장되어 있는 이슈 해결
---
이전 PR이 배포가 성공하면 해당 PR 머지하겠습니다.
---
https://no5ing.atlassian.net/browse/OING-313
=> [OING-313] hotfix: 기존 post의 데이터들이 type값이 FEED로 저장되어 있는 이슈 해결

post/src/main/java/com/oing/controller/PostController.java, post/src/main/java/com/oing/dto/response/MissionAvailableStatusResponse.java, post/src/main/java/com/oing/dto/response/MissionEligibleStatusResponse.java, post/src/main/java/com/oing/dto/response/SurvivalUploadStatusResponse.java, post/src/main/java/com/oing/restapi/PostApi.java
---
회원 생존신고 게시글 업로드 여부 / 회원 미션 참여 가능 여부 확인하는 mock API를 추가했습니다.
---
- 회원 생존신고 게시글 업로드 여부 확인 mock API 추가
- 회원 미션 참여 가능 여부 확인 mock API 추가
---
프론트에서 mock api더라도 query parameter로 응답값 조작이 가능하길 원하셔서 임시적으로 query parameter를 추가했습니다. 추후, 실제 구현 때는 해당 파라미터를 제거할 예정입니다.
uri 결정하면서 고민을 했는데 API의 행동이 더 명확하게 보이는 uri가 있다면 추천해주세요~
---
https://no5ing.atlassian.net/browse/OING-314
=> [OING-314] feature: 회원 생존신고 게시글 업로드 여부 / 회원 미션 참여 가능 여부 확인 mock API 추가

post/src/main/java/com/oing/service/PostService.java
---
기존 로그에 포스트 중복 작성 검증 로직에 today 날짜 확인 가능하도록 추가했습니다.
---
- 포스트 중복 작성 검증 로그에 today 날짜 추가
---
빠른 디버깅을 위해 바로 머지하겠습니다.
---
https://no5ing.atlassian.net/browse/OING-322
=> [OING-322] refactor: 포스트 중복 작성 검증 로그에 today 날짜 추가

gateway/src/main/java/com/oing/controller/MainViewController.java, gateway/src/main/java/com/oing/dto/response/MainPageTopBarResponse.java
---
NighttimeMainPage의 displayRank 필드는 기존 모두 1에서 NULL이 되도록 수정해달라는 프론트엔드의 요청이 있었습니다.
---
- getNighttimeMainPage에서 displayRank 설정을 늘 전부 NULL이 되도록 수정
- Response DTO에서 displayRank의 야근시 값에 대한 설명 수정
---
프론트에 사이드이펙트 없도록 빠르게 해주시면 감사하겠습니다..!
---
https://no5ing.atlassian.net/browse/OING-324
=> [OING-324] refactor: NighttimeMainPage의 displayRank 필드는 늘 NULL이 되도록 수정

common/src/main/java/com/oing/service/MemberBridge.java, common/src/main/java/com/oing/service/MissionBridge.java, gateway/src/main/java/com/oing/controller/CalendarController.java, gateway/src/main/java/com/oing/restapi/CalendarApi.java, gateway/src/main/java/com/oing/service/MemberBridgeImpl.java, gateway/src/main/java/com/oing/service/MissionBridgeImpl.java, gateway/src/test/java/com/oing/controller/CalendarControllerTest.java, gateway/src/test/java/com/oing/restapi/CalendarApiTest.java, mission/src/main/java/com/oing/service/MissionService.java, post/src/main/java/com/oing/dto/response/DailyCalendarResponse.java, post/src/main/java/com/oing/dto/response/MonthlyCalendarResponse.java
---
미션 게시글이 추가됨에 따라, 주간(일별로 보는) 캘린더에서 생존신고 게시글 다음에 미션 게시글이 나타나는 정책이 추가되었고 미션 게시글 또한 캘린더 DTO에서 대응해야했습니다. 기존에는 프론트가 fetchPosts 공용 API를 이용해 게시글을 조회하고 이를 잘 가공하여 보여주는 방식이었는데, 공용 API의 기능이 이미 비대하고 새로운 기능들이 프론트에서 구현하기 복잡하여 프론트에 맞춘 뷰 기반 API를 추가했습니다.
---
- getCalendar API를 getMonthlyCalendar와 getDailyCalendar로 분리하고, getDailyCalendar를 구현 (API추가, DTO 추가, 필요한 비즈니스 코드 추가 및 연결)
- 테스트 코드 추가
---
프론트에서 계속 요청들어오는 부분이라 빠르게 부탁드려요!
---
https://no5ing.atlassian.net/browse/OING-323
=> [OING-323] feat: 일간 캘린더 API 추가

gateway/src/main/java/com/oing/controller/CalendarController.java, gateway/src/test/java/com/oing/restapi/CalendarApiTest.java, post/src/main/java/com/oing/dto/response/DailyCalendarResponse.java
---
DailyCalendarResponse에 PostResponse 필드를 추가해달라는 프론트 요청이 있었습니다.
---
- DailyCalendarResponse에 (postContent, authorId, commentCount, emojiCount, allFamilyMembersUploaded, createdAt) 필드 추가
---
---
https://no5ing.atlassian.net/browse/OING-328
=> [OING-328] feat: DailyCalendarResponse에 PostResponse 필드 추가 (프론트 요청)

gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java, gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java, gateway/src/test/java/com/oing/restapi/PostApiTest.java, post/src/main/java/com/oing/controller/PostController.java, post/src/main/java/com/oing/repository/PostRepositoryCustom.java, post/src/main/java/com/oing/restapi/PostApi.java, post/src/main/java/com/oing/service/PostService.java, post/src/test/java/com/oing/service/PostServiceTest.java
---
오늘 날짜 기준으로 가족 구성원 수를 계산하는 기존 미션 키 관련 검증 로직이 문제가 될 수 있어, 가족 구성원 수를 어제 날짜 기준으로 세도록 수정했습니다.
---
- 미션 검증 로직 중, 가족 구성원 수를 어제 날짜 기준으로 세도록 수정
---
추가적으로 수정해야 할 부분이 있다면 알려주세요~
---
https://no5ing.atlassian.net/browse/OING-329
=> [OING-329] refactor: 미션 검증 로직 중에서 가족 구성원 수 계산할 때, 어제 날짜 기준으로 세도록 수정

.github/workflows/dev-cicd.yaml, .github/workflows/prod-cicd.yaml, common/src/main/java/com/oing/exception/ErrorCode.java, gateway/src/test/java/com/oing/job/DailyMissionJobTest.java, gateway/src/test/java/com/oing/repository/DailyMissionHistoryRepositoryTest.java, gateway/src/test/java/com/oing/repository/MissionRepositoryTest.java, mission/src/main/java/com/oing/exception/DuplicatedDailyMissionHistoryException.java, mission/src/main/java/com/oing/job/DailyMissionJob.java, mission/src/main/java/com/oing/repository/DailyMissionHistoryRepository.java, mission/src/main/java/com/oing/repository/DailyMissionHistoryRepositoryCustom.java, mission/src/main/java/com/oing/repository/DailyMissionHistoryRepositoryCustomImpl.java, mission/src/main/java/com/oing/repository/MissionRepository.java, mission/src/main/java/com/oing/service/DailyMissionHistoryService.java, mission/src/main/java/com/oing/service/MissionService.java, mission/src/test/java/com/oing/service/DailyMissionHistoryServiceTest.java
---
임시로 API response와 Service code가 모킹되어 있던 것을 구현하였습니다. 스케줄러로 돌아가는 배치이기 때문에 검증하기 어렵고 비즈니스 상 중요한 로직이므로 새로운 형태의 테스트 코드들도 추가했습니다.
ps. 현재는 Spring Scheduler로 배치를 구현하였지만, 추후 Spring Batch로 리팩토링하게 될 예정입니다.
---
- 스케줄러와 테이블 락을 통한 일일 미션 선출 배치 구현
- Repository, Service, Job 에 대한 테스트 코드 추가
---
통합 테스트의 경우, 저희 멀티모듈 구조 상 Context loading을 할 수가 없어 에러가 발생하네요. 구글링을 통해 찾은 여러 우회 방법이 저의 케이스에서 동작하지 않아, 일단은 Gateway 모듈에 구현하였습니다. 혹시 이에 도움이 될만한 케이스가 있으면 공유 부탁드려요 🥲 @Ji-soo708 @CChuYong 
---
https://no5ing.atlassian.net/browse/OING-326
=> [OING-326] feat: 일일 미션 배치 구현 및 테스트코드 추가

mission/src/main/java/com/oing/restapi/MissionApi.java
---
버그 리포트되서 파악된 getMissionByMissionId에 입력 파라미터에 @PathVariable 누락을 해결했습니다.
---
- getMissionByMissionId에 입력 파라미터에 @PathVariable 누락 해결
---
---
https://no5ing.atlassian.net/browse/OING-332
=> [OING-332] fix: getMissionByMissionId에 입력 파라미터에 @PathVariable 누락 해결

gateway/src/main/java/com/oing/controller/MainViewController.java, gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java, gateway/src/main/resources/db/migration/V202405092310__add_createdAt_idx_in_post_tbl.sql, gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java, gateway/src/test/java/com/oing/restapi/MainViewApiTest.java, post/src/main/java/com/oing/controller/PostController.java, post/src/main/java/com/oing/repository/PostRepositoryCustom.java, post/src/main/java/com/oing/restapi/PostApi.java, post/src/main/java/com/oing/service/PostService.java
---
가족 구성원 랭킹에서 '지난 날 생존신고 보기' 버튼이 금월에 해당하며 금월에 업로드된 생존신고가 없다면 비활성화(null)된다는 정책이 확정되어, 이를 반영하는 PR입니다.
---
- 정해진 기간동안 가장 최근 생존신고를 조회하는 findRecentPost API 추가
- findRecentPost를 이용해 가족 구성원 랭킹 수정
- findRecentPost 쿼리에 대한 테스트 코드 추가
---
---
https://no5ing.atlassian.net/browse/OING-330
=> [OING-330] feat: 가족 구성원 랭킹에서 '지난 날 생존신고 보기'에 대한 보충 정책 반영

gateway/src/main/java/com/oing/controller/MainViewController.java
---
프론트의 요청으로 탈퇴한 회원 정보 값을 "UNKNOWN"이 아닌 null 값을 주도록 수정했습니다.
---
- 탈퇴한 회원 정보 값을 "UNKNOWN"이 아닌 null 값을 주도록 수정
---
리뷰부탁드림다
---
https://no5ing.atlassian.net/browse/OING-333
=> [OING-333] feature: 탈퇴한 회원 정보 값으로 "UNKNOWN"이 아닌 null 값을 주도록 수정

gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java, post/src/main/java/com/oing/controller/PostController.java, post/src/main/java/com/oing/repository/PostRepositoryCustom.java, post/src/main/java/com/oing/service/PostService.java
---
3.0 QA 에서 가족구성원 랭킹 API의 생존신고 수가 미션 수를 포함하는 현상이 리포트되었습니다.
버그를 고치기 위해 쿼리를 수정하던 중 지난 번에 생성한 Post CreatedAt 인덱스를 탈 수 있도록 비교 쿼리를 리팩토링했습니다.
---
- 리포트 된 버그를 고치기 위해 PostType.Survival 비교 연산자 추가
- CreatedAt에서 year(), month()를 별도로 추출해서 equals 비교하는 연산자에서 인덱스를 타기 위해 between 연산자로 리팩토링
---
파이팅
---
https://no5ing.atlassian.net/browse/OING-335
=> [OING-335] fix: 가족구성원 랭킹 API의 생존신고 수가 미션 수를 포함하는 현상 해결

gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java, member/src/main/java/com/oing/controller/MemberController.java, post/src/main/java/com/oing/service/PostService.java
---
- 푸쉬 알림 컨텐츠 변경 및 경로 추가
---
- 푸쉬 알림 (콕 찌르기) 컨텐츠 변경
- 미션 업로드 시 노티 발송
---
백엔드 PR 엄청 오랜만이네요 ㄷㄷ
따로 일별로 미션 푸쉬 발송 여부를 디비에 쌓는것도 이상해보여서 로직과 같이 바로 "이전 게시물은 조건 미만족 && 새 게시물 포함하면 미션 조건 만족" 일때 푸쉬 발송하게 해놨는데.. 이론상은 맞는데 혹시 엣지케이스 떠오르는거 있으면 코멘트 부탁드립니다.
---
https://no5ing.atlassian.net/browse/OING-336
=> [OING-336] feat: 푸쉬 알림 메세지 변경 및 미션 업로드 시 노티 발송

gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
---
위젯에서 미션글은 노출되지 않는 점을 해결하기 위해 작업을 진행하였고, PostRepositoryCustomImpl에서 findLatestPostOfEveryday와 findOldestPostOfEveryday 쿼리에 PostType.eq(SURVIVAL) 절이 의도와 다르게 추가된 점을 발견해 수정하였습니다. 3.0차에 미션을 도입하기 위해 추가한 PostType 컬럼을 도입하며 쿼리들을 리팩토링하는 과정에서 잘못 들어간 것으로 보입니다.
---
- PostRepositoryCustomImpl의 findOldestPostOfEveryday, findLatestPostOfEveryday 쿼리에서 PostType.eq(SURVIVAL) 비교절 제거
---
---
https://no5ing.atlassian.net/browse/OING-337
=> [OING-337] fix: 위젯에서 미션글도 보이도록 수정 (PostRepositoryCustomImpl에서 잘못 추가된 PostType 비교절 제거)

common/src/main/java/com/oing/service/FamilyBridge.java, common/src/main/java/com/oing/service/MemberBridge.java, common/src/main/java/com/oing/service/PostBridge.java, family/src/main/java/com/oing/domain/Family.java, family/src/main/java/com/oing/domain/FamilyInviteLink.java, family/src/main/java/com/oing/dto/response/FamilyInviteDeepLinkResponse.java, family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java, family/src/main/java/com/oing/service/FamilyInviteLinkService.java, family/src/main/java/com/oing/service/FamilyService.java, gateway/src/main/java/com/oing/controller/DeepLinkController.java, gateway/src/main/java/com/oing/controller/FamilyInviteViewController.java, gateway/src/main/java/com/oing/domain/DeepLink.java, gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java, gateway/src/main/java/com/oing/restapi/DeepLinkApi.java, gateway/src/main/java/com/oing/service/DeepLinkService.java, gateway/src/main/java/com/oing/service/FamilyBridgeImpl.java, gateway/src/main/java/com/oing/service/MemberBridgeImpl.java, gateway/src/main/resources/db/migration/V202406171820__add_column_to_deep_link_and_family_invite_link_tbl.sql, gateway/src/main/resources/db/migration/V202406171920__add_family_name_column_to_family_tbl.sql, gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java, gateway/src/test/java/com/oing/repository/MemberRepositoryCustomTest.java, gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java, member/src/main/java/com/oing/controller/MemberController.java, member/src/main/java/com/oing/repository/MemberRepository.java, member/src/main/java/com/oing/repository/MemberRepositoryCustom.java, member/src/main/java/com/oing/repository/MemberRepositoryCustomImpl.java, member/src/main/java/com/oing/restapi/MemberApi.java, member/src/main/java/com/oing/service/MemberService.java, post/src/main/java/com/oing/repository/PostRepositoryCustom.java, post/src/main/java/com/oing/service/PostBridgeImpl.java
---
가족 초대 딥링크 발급 로직 변경 및 가족 초대 뷰 기반 API 실제 로직 추가했습니다.
---
- 가족/딥링크 테이블 변경
- 가족 초대 딥링크 발급 로직 변경
- 가족 초대 뷰 기반 API 실제 로직 추가
---
추가된 코드가 많아 커밋 별로 보시면 편합니다.
---
https://no5ing.atlassian.net/browse/OING-340
=> [OING-340] feature: 가족 초대 딥링크 발급 로직 변경 및 가족 초대 뷰 기반 API 실제 로직 추가

gateway/src/main/java/com/oing/controller/FamilyInviteViewController.java
---
딥링크 초대 뷰 API에서 memberId == null 인 경우 isRequesterJoinedFamily가 false가 되도록 추가했습니다
---
- memberId == null 인 경우 추가
---
memberId == null인지 불린값 주는 응답 필드가 하나 더 필요하다면 알려주세요~
---
https://no5ing.atlassian.net/browse/OING-342
=> [OING-342] refactor: 딥링크 초대 뷰 API에서 memberId == null 인 경우 추가

family/src/main/java/com/oing/domain/Family.java, family/src/main/java/com/oing/dto/request/UpdateFamilyNameRequest.java, family/src/test/java/com/oing/service/FamilyServiceTest.java, gateway/src/main/resources/V202406261718__alter_family_name_column_type.sql
---
`family_name` 컬럼을 아홉자까지 허용하도록 수정하고 `familyName`을 초기화해도 수정자가 기록되도록 수정했습니다.
---
- `family_name` 컬럼을 아홉자까지 허용
- `familyName`을 초기화해도 수정자가 기록되도록 수정
---
확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-343
=> [OING-343] refactor: 가족 이름 컬럼 타입 및 검증 로직 수정

gateway/src/main/resources/db/migration/V202406291302__alter_family_invite_link_pk.sql
---
가족 초대 링크 테이블 migration file에서 primary key가 다르게 설정되어 있어 운영서버에서 장애를 일으키는 걸 확인하고 수정했습니다.
---
- 가족 초대 링크 잘못된 primary key 변경
---
핫픽스라 바로 머지하겠습니다.
---
https://no5ing.atlassian.net/browse/OING-345
=> [OING-345] hotfix: 가족 초대 링크 잘못된 primary key 변경

post/src/main/java/com/oing/controller/VoiceCommentController.java, post/src/main/java/com/oing/domain/CommentType.java, post/src/main/java/com/oing/dto/response/PostCommentResponseV2.java, post/src/main/java/com/oing/dto/response/PostVoiceCommentResponse.java, post/src/main/java/com/oing/restapi/VoiceCommentApi.java
---
음성 댓글 관련 API 목을 추가했어요.
---
- 음성 댓글 추가, 삭제, 조회 API 목 추가
---
오랜만에 쓰네요 ㅎㅎㅎ
---
https://no5ing.atlassian.net/browse/OING-375
=> [OING-375] feat: 음성 댓글 관련 API 목을 추가해요

gateway/src/main/java/com/oing/controller/NotificationController.java, gateway/src/main/java/com/oing/domain/NotificationStyle.java, gateway/src/main/java/com/oing/dto/response/NotificationResponse.java, gateway/src/main/java/com/oing/restapi/NotificationApi.java
---
음성 댓글에 이어, 알림 관련 API 목을 추가했어요.
---
- 현재 볼 수 있는 알림 조회 API 추가
---
화이팅!
---
https://no5ing.atlassian.net/browse/OING-376
=> [OING-376] feat: 알림 관련 API 목을 추가해요

post/src/main/java/com/oing/controller/VoiceCommentController.java, post/src/main/java/com/oing/dto/request/CreatePostVoiceCommentRequest.java, post/src/main/java/com/oing/restapi/VoiceCommentApi.java, post/src/main/java/com/oing/service/VoiceCommentService.java, post/src/test/java/com/oing/service/VoiceCommentServiceTest.java
---
프론트의 요청으로 기존에 사용하던 `CreatePostCommentRequest` 대신 `CreatePostVoiceCommentRequest`로 수정했습니다
---
- saveVoiceComment RequestBody 변경
---
확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-383
---
https://no5ing.atlassian.net/browse/OING-383
=> [OING-383] refact: saveVoiceComment RequestBody 변경

gateway/src/main/java/com/oing/dto/response/NotificationResponse.java, gateway/src/main/java/com/oing/service/MemberNotificationHistoryService.java
---
프론트의 요청으로 NotificationResponse에 발송자 memberId를 추가했습니다
---
- NotificationResponse에 발송자 memberId 추가
---
< 여기에 하고싶은 말 >
---
https://no5ing.atlassian.net/browse/OING-386
=> [OING-386] refactor: NotificationResponse에 발송자 memberId 추가

gateway/src/main/resources/db/migration/V202503281417__add_index_receiver_created_at_to_member_notification_history.sql
---
`member_notification_history` 테이블 `receiver_member_id`, `created_at` 인덱스 추가
---
- `member_notification_history` 테이블 `receiver_member_id`, `created_at` 인덱스 추가
---
인덱스 추가 작업이라 바로 머지하겠습니다
---
https://no5ing.atlassian.net/browse/OING-391
=> feat: member_notification_history 테이블 receiver_member_id, created_at 인덱스 추가
