.github/workflows/build.yaml
.github/workflows/deploy.yaml
.github/workflows/dev.yaml
.github/workflows/prod.yaml
config/build.gradle
member/src/main/java/com/oing/controller/MemberController.java

---
프로젝트 CI/CD 구축을 위함
---
CD 파이프라인이 추가되었습니다
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-16?atlOrigin=eyJpIjoiNjdmOWIyZDZjYTdjNDVjMGE4YTcwOTNkM2MyYmIzODYiLCJwIjoiaiJ9

[OING-16] chore: 프로젝트 CD 파이프라인 추가

---

.github/workflows/dev.yaml
.github/workflows/prod.yaml
common/build.gradle
common/src/main/java/com/oing/domain/exception/DomainException.java
common/src/main/java/com/oing/domain/exception/ErrorCode.java
common/src/main/java/com/oing/dto/response/ErrorResponse.java
common/src/test/java/com/oing/domain/exception/DomainExceptionTest.java
common/src/test/java/com/oing/dto/response/ErrorResponseTest.java
config/build.gradle
settings.gradle

---
각 모듈별 공통적으로 들어가는 공통 모듈이 필요했습니다.
---
- 공통 모듈을 추가하였습니다
- 공통 모듈을 액션 워크플로우에 추가하였습니다
- 공통 예외 (Exception) 및 에러코드 클래스를 생성하였습니다.
- 공통 에러 응답 DTO를 추가하였습니다.
---
처음 코드가 들어가는 PR이네요 ㅎㅅㅎ
---
https://no5ing.atlassian.net/browse/OING-18

[OING-18] feat: 공통 모듈 구축하기

---

config/src/main/java/com/oing/ServerApplication.java
config/src/main/java/com/oing/config/SpringSecurityConfig.java
config/src/main/java/com/oing/config/SpringWebConfig.java
config/src/main/java/com/oing/config/SpringWebExceptionHandler.java
config/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
config/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
config/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
config/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
config/src/main/java/com/oing/config/properties/WebHeaderNameProperties.java
config/src/main/java/com/oing/config/properties/WebProperties.java
config/src/main/resources/application.yaml
settings.gradle

---
프로젝트 기본 개발환경중 스프링 시큐리티 & 웹 관련 보일러플레이트가 필요했습니다.
---
- 요청에 대한 간단한 로그 기능이 추가되었습니다.
- 스프링 시큐리티를 JWT대응을 위해 Sesionless 모드로 설정하였습니다.
- 기본 스프링 시큐리티 핸들러/필터 를 추가하였습니다.
- 웹 예외 핸들러를 추가하였습니다.
---
보일러플레이팅이다보니 한 피쳐에 커밋과 파일체인지가 좀 많습니다..ㅠㅠ
양해 부탁드립니다!
---
https://no5ing.atlassian.net/browse/OING-19

[OINT-19] feature: 스프링 시큐리티 설정

---

build.gradle
config/build.gradle

---
code coverage를 측정하기 위해 프로젝트에 Jacoco를 도입했습니다. 해당 PR이 merge된 후에 SonarQube(SonarCloud)를 세팅할 예정입니다.
---
- 프로젝트에 Jacoco 도입
---
리뷰 잘부탁드립니다 ☺️
---
https://no5ing.atlassian.net/browse/OING-10

[OING-10] chore: code coverage를 위한 Jacoco 설정

---

config/build.gradle
config/src/main/java/com/oing/config/JWTTokenGenerator.java
config/src/main/java/com/oing/config/authentication/APIKeyAuthentication.java
config/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
config/src/main/java/com/oing/config/properties/TokenExpirationProperties.java
config/src/main/java/com/oing/config/properties/TokenProperties.java
config/src/main/resources/application.yaml
member/src/main/java/com/oing/domain/TokenPair.java
member/src/main/java/com/oing/domain/exception/TokenNotValidException.java
member/src/main/java/com/oing/service/TokenGenerator.java
member/src/test/java/com/oing/domain/TokenPairTest.java
member/src/test/java/com/oing/domain/exception/TokenNotValidExceptionTest.java

---
유저 인증 절차 관리를 위해 JWT 및 부속 컴포넌트가 필요했습니다.
---
- JWT 생성, 검증용 컴포넌트 추가
- JWT 토큰 유효성 관련 Properties 추가
- JWT 토큰 검증 관련 Exception 추가
- 추가된 클래스 유닛테스트 추가
---
잘부탁드립니다
---
https://no5ing.atlassian.net/browse/OING-20

[OING-20] feat: JWT 토큰 관리 컴포넌트 생성

---

.github/workflows/dev.yaml
.github/workflows/prod.yaml
config/build.gradle
family/build.gradle
post/build.gradle
settings.gradle

---
작업들이 모두 모듈위에서 이루어져야해서 모듈을 추가하였습니다.
---
- Post 모듈 추가
- Member 모듈 추가
- 각 모듈별 gradle, workflow 설정 변경
---
화이팅합시다
---
https://no5ing.atlassian.net/browse/OING-46

[OING-46] feat: Member, Post 모듈 추가하기

---

common/src/main/java/com/oing/domain/model/BaseAuditEntity.java

---
팻핑거가 발생했습니다
---
한줄 지우기
---
ㅠㅠ
---
https://no5ing.atlassian.net/browse/OING-57

[OING-57] hotfix: Member 도메인 entity & repository 구성 오타

---

common/src/main/java/com/oing/dto/response/PaginationResponse.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/restapi/PostApi.java

---
API 경로가 변경되어야했습니다.
---
- /feeds -> /posts 가 되었습니다
- PaginationResponse에 hasNext 필드가 추가되었습니다
---
화이팅!
---
https://no5ing.atlassian.net/browse/OING-40

[OING-40] feature: API 경로 변경 및 Response DTO 변경

---

family/src/main/java/com/oing/controller/FamilyController.java
family/src/main/java/com/oing/domain/Family.java
family/src/main/java/com/oing/repository/FamilyRepository.java
family/src/main/java/com/oing/restapi/FamilyApi.java
family/src/main/java/com/oing/service/FamilyService.java

---
Family 도메인 DDL 기반 모델을 구성했습니다.
---
- Family domain 추가
- Family repository 추가
- Family api, controller 추가
---
디렉토리 구조에 대해서 서로 점검하면 좋겠네요 🙏
---
https://no5ing.atlassian.net/browse/OING-56?atlOrigin=eyJpIjoiOGE1YzdhZWUxYzJlNDQ0Y2FmYTI0MGJlMDFlNTdiMzAiLCJwIjoiaiJ9

[OING-56] feat: Family 모듈 구성

---

common/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
gateway/src/test/java/com/oing/component/JWTTokenGeneratorTest.java
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/restapi/MemberApi.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/restapi/PostApi.java

---
피드 사진 업로드를 위한 PresignedUrl 요청 API를 구현했습니다. 
해당 요청을 통해 얻은 url에 PUT 요청으로 이미지를 전송하면 버킷에 이미지가 저장됩니다.
---
- PresignedUrl 요청 API 구현
---
회원만 이용가능하도록 해야해서 해당 요청 경로를 `url-whitelists`에 추가 안했습니다. 테스트하시고 싶다면 리스트에 추가하고 수행하면 됩니다.

[OING-66] feat: PresignedUrl 요청 API 구현

---

family/src/main/java/com/oing/controller/FamilyController.java
family/src/main/java/com/oing/dto/response/FamilyInvitationLinkResponse.java
family/src/main/java/com/oing/dto/response/FamilyMonthlyStatisticsResponse.java
family/src/main/java/com/oing/dto/response/FamilyResponse.java
family/src/main/java/com/oing/restapi/FamilyApi.java
gateway/src/main/java/com/oing/config/SwaggerConfig.java
member/src/main/java/com/oing/controller/AuthController.java
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/dto/request/UpdateMemberRequest.java
member/src/main/java/com/oing/restapi/AuthApi.java
member/src/main/java/com/oing/restapi/MemberApi.java
post/src/main/java/com/oing/controller/CalendarController.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/controller/PostReactionController.java
post/src/main/java/com/oing/dto/request/CreatePostReactionRequest.java
post/src/main/java/com/oing/dto/request/CreatePostRequest.java
post/src/main/java/com/oing/dto/response/CalendarResponse.java
post/src/main/java/com/oing/dto/response/PostResponse.java
post/src/main/java/com/oing/restapi/CalendarApi.java
post/src/main/java/com/oing/restapi/PostApi.java
post/src/main/java/com/oing/restapi/PostReactionApi.java
post/src/test/java/com/oing/dto/response/PostFeedResponseTest.java

---
MVP에 필요한 API를 설계해야했습니다
---
- 필요 API 문서 추가
- API 경로에 dev. 추가
- 임시 토큰 발행 API 추가
---
감사합니다

[OING-63] feat: 1차 와이어프레임 API 설계

---

family/src/main/java/com/oing/controller/FamilyController.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/restapi/PostApi.java

---
1차 출시를 위한 API 모킹
---
- Family 모듈 모킹
- Post 모듈 모킹
---
화이팅입니다

[OING-73] feat: family, post api mock 구현

---

member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/dto/request/UpdateMemberRequest.java
member/src/main/java/com/oing/restapi/MemberApi.java

---
회원 정보 수정 API 모킹을 했습니다.
---
- 회원정보 수정 API 모킹
---
수정해야할 부분이 있는 지 확인해주세요. 리뷰 감사합니다~

[OING-71] feat: 회원정보 수정 API 모킹

---

post/src/main/java/com/oing/controller/PostReactionController.java
post/src/main/java/com/oing/dto/request/CreatePostReactionRequest.java
post/src/main/java/com/oing/dto/request/PostReactionRequest.java
post/src/main/java/com/oing/restapi/PostReactionApi.java

---
포스트에 리액션 남기기/삭제 API를 모킹했습니다.
---
- 포스트에 리액션 남기기 API 모킹
- 포스트에 남긴 리액션 삭제 API 모킹
---
포스트에 리액션 남기는 API의 이름의 경우, 통일성을 주기 위해 변경했습니다. 리뷰 잘부탁드려요~

[OING-68] feat: Post Reaction API 모킹

---

post/src/main/java/com/oing/controller/PostReactionController.java
post/src/main/java/com/oing/domain/Emoji.java
post/src/main/java/com/oing/domain/model/MemberPostReaction.java
post/src/main/java/com/oing/dto/request/PostReactionRequest.java
post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java

---
바뀐 ui를 참고하여 5개의 이모지명을 바꾸고 Emoji 타입을 Enum으로 변경하였습니다.
---
- 이모지명 변경
- Emoji 타입 변경
---
리뷰 잘부탁드립니다~

[OING-88] feat: Emoji Enum 타입으로 변경

---

gateway/src/main/java/com/oing/controller/CalendarController.java
gateway/src/main/java/com/oing/controller/WidgetController.java
member/src/main/java/com/oing/service/MemberService.java

---
MemberService 및 WidgetController에서의 컴파일 에러를 해결했습니다.
---
- MemberService 및 WidgetController에서의 컴파일 에러 해결
---
---
https://no5ing.atlassian.net/browse/OING-90

[OING-90] hotfix: MemberService 및 WidgetController에서의 컴파일 에러

---

post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/dto/response/PostResponse.java
post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
post/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
post/src/main/java/com/oing/service/MemberPostService.java

---
1차 mvp 출시를 위함
---
- GET v1/posts/{postId} 추가
- GET v1/posts 추가
---
메리 크리스마스
---
https://no5ing.atlassian.net/browse/OING-77

[OING-77] feat: Post 조회 관련 API 구현

---

common/src/main/java/com/oing/domain/exception/ErrorCode.java
common/src/main/java/com/oing/util/RandomStringGenerator.java
family/src/main/java/com/oing/controller/FamilyController.java
family/src/main/java/com/oing/domain/model/Family.java
family/src/main/java/com/oing/domain/model/FamilyInviteLink.java
family/src/main/java/com/oing/dto/response/FamilyResponse.java
family/src/main/java/com/oing/exception/FamilyNotFoundException.java
family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java
family/src/main/java/com/oing/service/FamilyInviteLinkService.java
family/src/main/java/com/oing/service/FamilyService.java
gateway/src/main/resources/db/migration/V3__create_FamilyInviteLink.sql

---
1차 mvp에 필요한 기능 구현
---
- POST /v1/families 추가
- GET /v1/families/{familyId}/invitation-link 추가
---
야호 종강이다
---
https://no5ing.atlassian.net/browse/OING-81

[OING-81] feat: v1/families 관련 API 구현

---

gateway/src/main/java/com/oing/restapi/CalendarApi.java
post/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java

---
CalendarApi와 관련된 에러와 잘못된 설정 해결
---
- QueryDSL DTO Projection runtime error 해결
- params required 설정 수정
- CalendarApi의 필수 type params 에 대한 설명 명시
---
파이팅...
---
https://no5ing.atlassian.net/browse/OING-97

[OING-97] CalendarApi와 관련된 에러와 잘못된 설정 해결

---

post/src/main/java/com/oing/domain/MemberPostCountDTO.java

---
#54  핫픽스2..
---
#54 핫픽스2..
---
너무 사소해서 바로 머지부탁드려요..
---
https://no5ing.atlassian.net/browse/OING-97

[OING-97] PR54 힛픽스 2

---

common/src/main/java/com/oing/domain/exception/ErrorCode.java
member/src/main/java/com/oing/dto/request/CreateNewMemberRequest.java
member/src/main/java/com/oing/dto/request/UpdateMemberProfileImageUrlRequest.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/dto/request/CreatePostRequest.java
post/src/main/java/com/oing/dto/response/PostResponse.java
post/src/main/java/com/oing/exception/DuplicatePostUploadException.java
post/src/main/java/com/oing/service/MemberPostService.java

---
영민님과 순찬이 남기신 코멘트를 보고 리팩터링했습니다.
---
- createPost 코드 개선
- 한 사람이 하루에 두 개 이상의 글을 작성 시도 시, DuplicatePostUploadException 예외 반환
---
추가적으로 수정해야할 부분이 있다면 알려주세요~
---
https://no5ing.atlassian.net/browse/OING-94

[OING-94] fix: createPost 코드 개선

---

member/src/main/java/com/oing/domain/SocialLoginProvider.java
member/src/main/java/com/oing/dto/response/KakaoAuthResponse.java
member/src/main/java/com/oing/service/AuthService.java

---
카카오 로그인이 필요하다고 합니다
---
카카오 로그인 기능을 추가하였습니다
---
메리 크리스마스
---
https://no5ing.atlassian.net/browse/OING-95

[OING-95] feat: 카카오 인증(로그인) 기능 구현

---

gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/restapi/MeApi.java
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/dto/response/MemberResponse.java

---
앱을 만들다가 생각해보니 저 API가 없었습니다
---
- GET /v1/me/member-info 가 추가되었습니다
- MemberResponse에 누락된 familyId등이 추가되었습니다
---
화이팅!
---
https://no5ing.atlassian.net/browse/OING-100

[OING-100] feat: 내 정보 조회 API & MemberResponse 누락필드 추가

---

post/src/main/java/com/oing/service/MemberPostService.java

---
POST조회시 전체 개수를 페이지 수로 내려주는 이슈가 있었습니다.
---
이슈를 해결하였습니다
---
추워요
---
https://no5ing.atlassian.net/browse/OING-101

[OING-101] hotfix: Post 조회시 페이지 수 카운트 이슈

---

family/src/main/java/com/oing/controller/FamilyController.java
family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java
family/src/main/java/com/oing/service/FamilyInviteLinkService.java

---
이미 있는 링크 검증을 안했습니다
---
이미 있으면 기발급된 링크를 반환합니다
---
안녕하세요
---
https://no5ing.atlassian.net/browse/OING-102

[OING-102] hotfix: Family 초대 링크 기발급 경우 기존 링크 반환

---

gateway/src/main/resources/application.yaml
member/src/main/java/com/oing/controller/AuthController.java
member/src/main/java/com/oing/service/MemberService.java

---
기존 임시 토큰으로 회원가입이 불가능하던 이슈를 해결하였습니다
---
- 화이트리스트 url 분리
- 토큰 검증 절차 추가
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-107

[OING-107] 임시 토큰 통한 회원가입 불가 이슈 해결

---

common/src/main/java/com/oing/dto/response/DefaultResponse.java
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/restapi/MemberApi.java
post/src/main/java/com/oing/controller/PostReactionController.java
post/src/main/java/com/oing/restapi/PostReactionApi.java

---
응답값이 empty일경우 클라이언트 파싱에서 문제가 발생한다고 하여 추가하였습니다
---
- DefaultResponse 추가
- void 형태 리턴 api defaultresponse 반환
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-108

[OING-108] feature: 응답값 없는 Operation의 기본 응답값 추가

---

common/src/main/java/com/oing/util/PreSignedUrlGenerator.java
gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
gateway/src/main/java/com/oing/controller/CalendarController.java
gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java
gateway/src/main/resources/db/migration/V202401021925__add_imgKey_column.sql
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/domain/model/Member.java
member/src/test/java/com/oing/domain/model/MemberTest.java
member/src/test/java/com/oing/domain/model/SocialMemberTest.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/domain/model/MemberPost.java
post/src/main/java/com/oing/dto/response/PostResponse.java
post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java
post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
post/src/test/java/com/oing/domain/model/MemberPostTest.java

---
이미지 url 뿐만 아니라 key 값까지 저장하기로 하여 이미지를 필요로 하는 엔티티에 필드를 추가했습니다.
---
- Member, MemberPost 엔티티에 imageKey 필드 추가
- imageUrl에서 key를 추출하는 메서드 추가
- 프로필 이미지 수정 시, 기존 이미지를 ObjectStorage에서 삭제하는 로직을 삭제
---
리뷰 잘 부탁드립니다~
---
https://no5ing.atlassian.net/browse/OING-109

[OING-109] feat: Member, MemberPost 엔티티에 imageKey 필드 추가

---

common/src/main/java/com/oing/domain/SerializableDeepLink.java
common/src/main/java/com/oing/domain/exception/ErrorCode.java
common/src/main/java/com/oing/exception/LinkNotValidException.java
common/src/main/java/com/oing/service/DeepLinkDetailService.java
family/src/main/java/com/oing/controller/FamilyController.java
family/src/main/java/com/oing/domain/model/FamilyInviteLink.java
family/src/main/java/com/oing/exception/AlreadyInFamilyException.java
family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java
family/src/main/java/com/oing/restapi/FamilyApi.java
family/src/main/java/com/oing/service/FamilyInviteLinkService.java
gateway/src/main/java/com/oing/controller/DeepLinkController.java
gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/domain/DeepLink.java
gateway/src/main/java/com/oing/domain/DeepLinkType.java
gateway/src/main/java/com/oing/dto/request/JoinFamilyRequest.java
gateway/src/main/java/com/oing/dto/response/DeepLinkResponse.java
gateway/src/main/java/com/oing/repository/DeepLinkRepository.java
gateway/src/main/java/com/oing/restapi/DeepLinkApi.java
gateway/src/main/java/com/oing/restapi/MeApi.java
gateway/src/main/java/com/oing/service/DeepLinkService.java
gateway/src/main/resources/db/migration/V202401031101__add_deep_link_tbl.sql
member/src/main/java/com/oing/domain/model/Member.java

---
딥링크 타고 가입이나 다른 일을 하기 위해서 개발하였습니다
---
- 딥링크 생성/조회 API 추가
- 딥링크 가족 가입 API 구현
---
화이팅!
---
https://no5ing.atlassian.net/browse/OING-112

[OING-112] feat: 딥링크 API & 딥링크 가족 가입 API 구현

---

gateway/src/main/java/com/oing/config/SwaggerConfig.java
gateway/src/main/java/com/oing/config/filter/AppVersionFilter.java
gateway/src/main/java/com/oing/config/properties/WebProperties.java
gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
gateway/src/main/resources/application.yaml
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
post/src/main/java/com/oing/service/MemberPostService.java

---
내 가족 외의 게시물이 조회가 됐었습니다
---
- 내 가족 게시물만 조회 되도록
- 앱 키 설정 스웨거에 추가
- 앱 키 필터 콘피그에서 토글 가능하도록
---
배고파요
---
https://no5ing.atlassian.net/browse/OING-120

[OING-120] hotfix: 내 가족만 게시물 조회 가능하게 & 앱 키 스웨거 추가

---

common/src/main/java/com/oing/domain/exception/ErrorCode.java
gateway/src/main/java/com/oing/config/properties/WebHeaderNameProperties.java
member/src/main/java/com/oing/controller/AuthController.java
member/src/main/java/com/oing/exception/MemberAlreadyExistsException.java

---
기존 회원가입자 재 회원가입 에러 핸들링이 필요했습니다
---
- 기 회원가입자 재회원가입 방지
- JWT 토근 테스트 관련 에러 수정
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-118

[OING-118] hotfix: 기회원가입자 재회원가입 방지

---

post/src/main/java/com/oing/domain/model/MemberPost.java

---
8자 이하까지 가능한데 8자여도 예외가 터지도록 작성되어 있어 수정했습니다.
---
- post 내용 길이 검증 수정
---
제대로 수정했는지 확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-122

[OING-122] hotfix: post 등록 시, 내용 길이 검증 수정

---

gateway/src/main/java/com/oing/component/JWTTokenGenerator.java

---
리프레시 토큰 api가 작동하지 않았습니다
---
- 리프레시 토큰 안에 memberId가 누락되어 있었습니다
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-124

[OING-124] hotfix: 리프레시 api 작동 안함 해결

---

README.md
build.gradle
gateway/src/main/java/com/oing/config/SpringWebConfig.java
gateway/src/main/resources/application.yaml
member/src/main/java/com/oing/domain/SocialLoginProvider.java
member/src/main/java/com/oing/dto/response/GoogleAuthResponse.java
member/src/main/java/com/oing/service/AuthService.java

---
안드로이드에 따른 구글 oAuth 필요
---
- 구글 oAuth 추가
- 추가된 환경변수 서버에 적용
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-127

[OING-127] feat: 구글 oAuth 추가

---

gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java

---
getThumbnailUrlGenerator 오타 해결
---
getThumbnailUrlGenerator 오타 해결
---
---
https://no5ing.atlassian.net/browse/OING-133

[OING-133] hotfix: getThumbnailUrlGenerator 오타 해결

---

common/src/main/java/com/oing/service/MemberBridge.java
gateway/src/main/java/com/oing/controller/DeepLinkController.java
gateway/src/main/java/com/oing/service/MemberBridgeImpl.java

---
계속 슬랙 알림이 왔습니다
---
- 가족을 조회할 수 있는 공통 인터페이스 생성
- 공통 인터페이스 구현
- 가족 검증 추가
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-137

[OING-137] hotfix: 가족 검증 누락으로 인한 알 수 없는 오류 해결

---

gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
gateway/src/main/resources/application.yaml
post/src/main/java/com/oing/controller/MemberPostController.java
post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
post/src/main/java/com/oing/service/MemberPostService.java

---
링크 발급 관련 memberId 누락 이슈 해결
---
- 이슈 해결
- 핸들링 안된 오류 일부 throw 변경
---
감사합니다

[OING-138] hotfix: 링크 발급 관련 memberId 누락 이슈 해결

---

gateway/src/test/java/com/oing/restapi/CalendarApiTest.java

---
새로운 PR 에서 해당 테스트가 실패하는 것을 해결하기 위함
---
- 테스트 하기 위해 선핼되던 given 절의 요청들이 FamilyApi 쪽이 변경되면서 실패되던 원인을 파악 및 해결
---
@CChuYong @Ji-soo708 각자 PR 올리기 전에 테스트를 전체적으로 돌리거나 PR이 올라가면서 트리거되는 action을 점검하고 후처리로 해결해야할 것 같습니다~
현재 저희 멀티모듈에서는 test가 분리되어 있어 클릭 한 번으로 전부 테스트하기 번거러워 보이는데, 혹시 아이디어 있으신 분있으면 의견도 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-139

[OING-139] fix: 깨진 WidgetApi의 통합테스트 고침

---

common/src/main/java/com/oing/dto/response/ArrayResponse.java
common/src/main/java/com/oing/dto/response/PaginationResponse.java
common/src/main/java/com/oing/exception/ErrorCode.java
common/src/main/java/com/oing/service/MemberBridge.java
gateway/src/main/java/com/oing/service/MemberBridgeImpl.java
gateway/src/main/resources/application-test.yaml
gateway/src/test/java/com/oing/restapi/MemberPostCommentApiTest.java
post/src/main/java/com/oing/controller/MemberPostCommentController.java
post/src/main/java/com/oing/domain/MemberPost.java
post/src/main/java/com/oing/domain/MemberPostComment.java
post/src/main/java/com/oing/dto/request/CreatePostCommentRequest.java
post/src/main/java/com/oing/dto/request/UpdatePostCommentRequest.java
post/src/main/java/com/oing/dto/response/PostCommentResponse.java
post/src/main/java/com/oing/exception/MemberPostCommentNotFoundException.java
post/src/main/java/com/oing/repository/MemberPostCommentRepository.java
post/src/main/java/com/oing/repository/MemberPostCommentRepositoryCustom.java
post/src/main/java/com/oing/repository/MemberPostCommentRepositoryCustomImpl.java
post/src/main/java/com/oing/restapi/MemberPostCommentApi.java
post/src/main/java/com/oing/service/MemberPostCommentService.java
post/src/main/java/com/oing/service/MemberPostService.java
post/src/test/java/com/oing/controller/MemberPostCommentControllerTest.java
post/src/test/java/com/oing/service/MemberPostCommentServiceTest.java

---
댓글 기능이 필요했습니다.
---
- 댓글 CRUD API 설계 & 구현
- 구현한 API 테스트
---
실제 구현 30분 테스트 2시간ㅠㅠ
---
https://no5ing.atlassian.net/browse/OING-142

[OING-142] feat: 댓글 기능 설계 & 구현 & 테스트

---

gateway/src/main/resources/db/migration/V202401132338__create_MemberQuitReason.sql
gateway/src/test/java/com/oing/restapi/MemberApiTest.java
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/domain/MemberQuitReason.java
member/src/main/java/com/oing/domain/MemberQuitReasonType.java
member/src/main/java/com/oing/domain/key/MemberQuitReasonKey.java
member/src/main/java/com/oing/dto/request/QuitMemberRequest.java
member/src/main/java/com/oing/repository/MemberQuitReasonRepository.java
member/src/main/java/com/oing/restapi/MemberApi.java
member/src/main/java/com/oing/service/MemberQuitReasonService.java
member/src/test/java/com/oing/service/MemberQuitReasonServiceTest.java

---
회원 탈퇴에서 이유가 필요해요
---
- 회원 탈퇴 이유 항목 추가
- 테스트 코드 작성
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-143

[OING-143] feat: 회원탈퇴 이유 기능 추가

---

member/src/main/java/com/oing/dto/response/FamilyMemberProfileResponse.java
member/src/test/java/com/oing/controller/MemberControllerTest.java
member/src/test/java/com/oing/dto/response/FamilyMemberProfileResponseTest.java

---
프론트의 요청으로 가족 멤버 프로필 조회 응답에 생일 필드를 추가했습니다.
---
- 가족 멤버 프로필 조회 응답에 생일 필드 추가
---
리뷰 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-149

[OING-149] refactor: 가족 멤버 프로필 조회 응답에 생일 추가

---

gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/restapi/MeApi.java

---
와프에 보니 그룹 탈퇴 기능이 있었습니다
---
- 가족 탈퇴 기능 추가
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-144

[OING-144] feat: 가족 탈퇴 API 추가

---

gateway/src/main/java/com/oing/component/AppVersionCache.java
gateway/src/main/java/com/oing/config/SpringWebConfig.java
gateway/src/main/java/com/oing/config/support/AppKeyResolver.java
gateway/src/main/java/com/oing/config/support/RequestAppKey.java
gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/domain/AppVersion.java
gateway/src/main/java/com/oing/dto/response/AppVersionResponse.java
gateway/src/main/java/com/oing/restapi/MeApi.java
gateway/src/main/resources/application.yaml
gateway/src/main/resources/db/migration/V202401142002__add_isLatest_column.sql

---
이런게 있었습니다
---
- 현재 접속중인 버전 정보 조회 API 추가
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-146

[OING-146] feat: 현재 어플리케이션 최신버전 유무 API 추가

---

gateway/src/main/java/com/oing/controller/WidgetController.java

---
2차 MVP부터 위젯이 요청자 자신의 게시글도 노출하도록 기획이 변경되었습니다.
---
- 위젯이 요청자 게시글도 포함하도록 로직 변경
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-166

[OING-166] feat: 위젯이 자신의 게시글도 포함하도록 정책 변경

---

post/src/main/java/com/oing/dto/response/PostRealEmojiResponse.java

---
프론트의 요청으로 응답 필드를 추가했습니다.
---
- 게시물에 달린 리얼이모지 조회 응답에 이모지 타입 추가
---
리뷰 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-170

[OING-170] refactor: 게시물에 달린 리얼이모지 조회 응답에 이모지 타입 추가

---

gateway/src/main/java/com/oing/controller/CalendarController.java
gateway/src/main/java/com/oing/domain/BannerImageType.java
gateway/src/main/java/com/oing/dto/response/BannerResponse.java

---
배너 정책이 바뀜에 따라 서버 드리븐하게 UI를 정하게 되었습니다. 그에 맞게 API Spec과 모킹을 변경합니다.
---
- BannerResponse 리펙토링
- API 모킹부 리펙토링
---
파이팅..
---
https://no5ing.atlassian.net/browse/OING-165

[OING-165] 바뀐 배너 정책에 맞게 배너 API 모킹 변경

---

gateway/src/main/resources/db/migration/V202401281811__add_FamilyJoinAt_column.sql
gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java
gateway/src/test/java/com/oing/restapi/MemberApiTest.java
gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
gateway/src/test/java/com/oing/restapi/MemberPostCommentApiTest.java
gateway/src/test/java/com/oing/restapi/MemberPostReactionApiTest.java
gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java
gateway/src/test/java/com/oing/restapi/MemberRealEmojiApiTest.java
member/src/main/java/com/oing/domain/Member.java
member/src/main/java/com/oing/dto/response/FamilyMemberProfileResponse.java
member/src/main/java/com/oing/dto/response/MemberResponse.java
member/src/test/java/com/oing/controller/MemberControllerTest.java
member/src/test/java/com/oing/domain/model/MemberTest.java
member/src/test/java/com/oing/domain/model/SocialMemberTest.java
member/src/test/java/com/oing/dto/response/FamilyMemberProfileResponseTest.java

---
---
- 가입 일자 필드 추가 및 api 필드 추가
- 에 따른 테스트 수리
---
다들 몸조심하세요
---
https://no5ing.atlassian.net/browse/OING-174

[OING-174] feat: 사용자 그룹 가입 일자 필드 추가

---

gateway/src/main/java/com/oing/controller/WidgetController.java
gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java

---
안드 클라 측에서 SingleRecentPostWidget에 PostId 필드 추가를 요청했습니다.
---
- SingleRecentPostWidgetResponse에 PostId 추가
---
오네가이
---
https://no5ing.atlassian.net/browse/OING-179

[OING-179] refactor: SingleRecentPostWidget에 PostId 추가

---

family/src/main/java/com/oing/controller/FamilyController.java
family/src/main/java/com/oing/dto/response/FamilyMonthlyStatisticsResponse.java
family/src/main/java/com/oing/restapi/FamilyApi.java
gateway/src/main/java/com/oing/controller/CalendarController.java
gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
gateway/src/main/java/com/oing/restapi/CalendarApi.java
post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
post/src/main/java/com/oing/service/MemberPostService.java

---
캘린더 통계 API 추가가 필요했습니다
---
- 캘린더 통계 API 추가
---
테스트코드는 다음주에 할게요..ㅎㅎ
---
https://no5ing.atlassian.net/browse/OING-181

[OING-181] feat: 캘린더 통계 API 추가

---

gateway/src/main/resources/application-test.yaml
gateway/src/test/java/com/oing/support/EmbeddedRedisConfig.java

---
임베디드 레디스 포트 연결 로직과 테스트 레디스 포트를 수정했습니다.
---
- 임베디드 레디스 포트 연결 로직 수정
---
해당 로직은 [조졸두님 블로그](https://jojoldu.tistory.com/297) 참고했습니다~
---
https://no5ing.atlassian.net/browse/OING-185

[OING-185] chore: Embedded Redis 포트 연결 로직 수정

---

gateway/src/main/resources/application-dev.yaml
gateway/src/main/resources/application-prod.yaml

---
actuator endpoints 설정이 로컬 application.yml에만 적용되어 있어, 배포 환경용 application.yml 에도 설정을 추가했습니다.
---
- application-dev.yml에 설정 추가
- application-prod.yml에 설정 추가
---
ㅠㅠ
---
https://no5ing.atlassian.net/browse/OING-184

[OING-184] chore: dev와 prod 환경의 application.yml에 actuator endpoints 설정을 추가

---

build.gradle
gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
gateway/src/main/resources/application-dev.yaml
gateway/src/main/resources/application-prod.yaml
gateway/src/main/resources/application-test.yaml
gateway/src/main/resources/application.yaml
gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
gateway/src/test/java/com/oing/restapi/WidgetApiTest.java

---
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[RELEASE] release: 2차 MVP 기능 핫픽스 및 리팩터링 1.1.2

---

gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java

---
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[RELEASE] release: 사진 압축 쿼리 핫픽스, 마이너 릴리즈 1.1.3

---

README.md

---
2차 MVP를 진행하며 바뀐 서버 아키텍처를 업데이트했습니다.
---
- 리드미 업데이트
---
- 수정하거나 추가하고 싶은 내용이 있다면 해당 브랜치에 커밋해주세요
---
https://no5ing.atlassian.net/browse/OING-190

[OING-190] docs: 백엔드 리드미 업데이트

---

gateway/src/main/resources/application-test.yaml
gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
gateway/src/test/java/com/oing/support/EmbeddedRedisConfig.java
member/src/test/java/com/oing/domain/model/MemberTest.java

---
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >
---
https://no5ing.atlassian.net/browse/OING-188

[OING-188] fix: EmbeddedRedisConfig 로직을 이전 로직으로 롤백

---

gateway/src/main/java/com/oing/controller/CalendarController.java
gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/dto/request/CreateNewMemberRequest.java
member/src/main/java/com/oing/repository/MemberDeviceRepository.java
member/src/main/java/com/oing/repository/MemberRepository.java
member/src/main/java/com/oing/service/MemberDeviceService.java
member/src/main/java/com/oing/service/MemberService.java

---
조금전에 나간 1.1.4 핫픽스
---
- 회원가입 글자수 validation 관련 해결
- 노티 발송 체크 관련 해결
- FCM 등록시 사용자ID 확인
- 캘린더 로직 변경
---
ㄳ합니다

[HOTFIX] hotfix: v1.1.4 오류/이슈 긴급 핫픽스

---

README.md

---
백엔드 리드미를 업데이트했습니다.
---
- 백엔드 리드미 업데이트
---
확인해주세요.

docs: 백엔드 README.md 업데이트

---

README.md
member/src/main/java/com/oing/restapi/MemberApi.java
post/src/main/java/com/oing/domain/MemberPost.java

---
포스트 작성할 때 내용에 이모지 포함하면 제대로 글자수가 측정안되는 이슈, 잘못된 `@Valid` 사용 이슈를 해결했습니다.
---
- 포스트 글자수 검증 로직 수정
- `@Valid` 에서 `@Validated`로 수정
---
확인해주세요~

[HOTFIX/1.1.6] hotfix: Hotfix v1.1.6 릴리즈 

---

gateway/src/main/java/com/oing/controller/MeController.java

---
급하니 일단 생략
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[HOTFIX/1.1.6] Hotfix/1.1.6 급하니 일단 생략

---

README.md

---
리드미에 있는 아키텍처 자료를 업데이트 합니다.
---
- 자료 업데이트
---
8282
---
https://no5ing.atlassian.net/browse/OING-201

[OING-201] chore: 리드미의 아키텍처 업데이트

---

README.md

---
1차 MVP 이후 디자인이 수정되어 리드미도 업데이트했습니다.
---
- 리드미 업데이트
---
확인 부탁드려요~

docs: 수정된 디자인으로 리드미 업데이트

---

common/src/main/java/com/oing/service/FamilyScoreBridge.java
family/src/main/java/com/oing/service/FamilyService.java
gateway/src/main/java/com/oing/controller/CalendarController.java
gateway/src/main/java/com/oing/restapi/CalendarApi.java
gateway/src/main/java/com/oing/service/FamilyScoreBridgeImpl.java

---
라이브 서버에서 사용되서는 안되는 어드민용 베너 API를 삭제합니다. 대신해서 디비에 stored procedure를 사용해볼 예정입니다. 비정규화한 데이터에 대한 정합성 대책은 곧 대책을 세워볼 예정입니다.
---
- 어드민용 베너 API 삭제
---
https://no5ing.atlassian.net/browse/OING-228

[OING-228] refactor: 어드민용 베너 API 삭제

---

gateway/src/main/java/com/oing/controller/DevController.java

---
개발자용 API의 필요성
---
- force-token, delete post 부활
---
화이팅
---
https://no5ing.atlassian.net/browse/OING-229

[OING-229] feat: Dev 용 API 추가 (Prod환경 제외)

---

gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/resources/application.yaml

---
- 구체적인 로깅의 예시
---
- 를 작성해보았습니다
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-242

[OING-242] feat: 구체적인 로깅 예시 및 적용

---

gateway/src/main/resources/db/migration/V202402252319__alter_FamilyTopPercentageHistory_tbl.sql

---
dev 환경에서 flywaiy initialization 실패로 빌드 실패했네요
---
- PRIMARY KEY를 제대로 수정하도록 flyway sql 파일 수정
---
`Key column 'date' doesn't exist in table`
---
https://no5ing.atlassian.net/browse/OING-206

[OING-206] fix: 오류가 발생한 flyway initialization sql 파일 수정

---

gateway/src/main/java/com/oing/job/DailyNotificationJob.java

---
- 여러 인스턴스상 동일 스케쥴러 작동 방지
---
- 스케쥴러 락 걸기
---
감사합니다
---
https://no5ing.atlassian.net/browse/OING-243

[OING-243] feat: 노티 스케쥴러에도 스케쥴러 락 적용

---

.github/workflows/dev.yaml
.github/workflows/prod.yaml
gateway/src/main/java/com/oing/component/SentryGateway.java
gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
gateway/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
gateway/src/main/resources/application-dev.yaml
gateway/src/main/resources/application-prod.yaml
gateway/src/main/resources/application.yaml

---
#183 PR을 통해서 Dev 서버에 정상적용되는 것을 확인했습니다. 차후 추가 테스트나 성능 테스트 등등 운영 환경 모니터링 뿐만 아니라 개발 환경에도 활용할 수 있도록 하였고, exception 핸들링을 고도화했습니다.
---
- Sentry 배포 환경별로 배포 (bibbi-prod / bibbi-dev) (슬랙에 안내된 url과 Top secret 참고)
- SpringWebExceptionHandler에서 핸들링되지 않는 토큰 예외에 Sentry capture 추가
- Exception의 단순 stacktrace 뿐 아니라, request의 자세한 정보를 추적하기 위해 SentryGateway 추가
---
Exception message가 없을경우 기본적인 메시지만 로깅됩니다. 각자 예외를 추가한다면, 추후 유지보수를 위해 자세히 기록부탁드려요.
---
https://no5ing.atlassian.net/browse/OING-208

[OING-208] feat: Sentry 고도화

---

gateway/src/main/java/com/oing/component/JWTTokenGenerator.java
gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
gateway/src/main/java/com/oing/job/DailyNotificationJob.java
member/src/main/java/com/oing/exception/TokenExpiredException.java

---
BE UNKNOWN ERROR 등 예외 해결 
---
- JWT 토큰 경우별 예외 분리
- Sentry에 사용자 정보 추가
- 스케쥴러 락 누락된거 추가
---
화이팅
---
https://no5ing.atlassian.net/browse/OING-255

[OING-255] feat: BE UNKNOWN ERROR 등 예외 해결 

---

gateway/src/test/java/com/oing/restapi/MemberApiTest.java

---
누락된 멤버 API 통합테스트 코드를 추가했습니다.
---
- 누락된 멤버 API 통합테스트 코드 추가
---
확인해주세요~
---
https://no5ing.atlassian.net/browse/OING-248

[OING-248] test: 누락된 멤버 API 통합테스트 코드 추가

---

gateway/build.gradle
gateway/src/main/java/com/oing/config/RedisConfig.java
gateway/src/main/resources/application-prod.yaml
gateway/src/main/resources/application.yaml

---
AWS 프로덕션용 설정 일부 변경
---
- 일부 컨테이너 스펙 변경
- 로그 포맷 변경
- 메모리 설정 변경
- REDIS 설정 변경
---
ㅎㅇㅌ
---
https://no5ing.atlassian.net/browse/OING-215

[OING-215] feat: AWS 프로덕션용 설정 일부 변경

---

gateway/src/main/java/com/oing/config/authentication/JWTTokenAuthentication.java
gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
gateway/src/main/java/com/oing/controller/AdminController.java
gateway/src/main/java/com/oing/domain/DateCountProjection.java
gateway/src/main/java/com/oing/dto/response/AdminDailyDashboardResponse.java
gateway/src/main/java/com/oing/dto/response/AdminDashboardResponse.java
gateway/src/main/java/com/oing/dto/response/DashboardDistributionResponse.java
gateway/src/main/java/com/oing/dto/response/DashboardValueResponse.java
gateway/src/main/java/com/oing/repository/DashboardRepositoryCustomImpl.java
gateway/src/main/java/com/oing/restapi/AdminApi.java

---
어드민 대시보드용 API가 필요했습니다
---
- 대시보드 API 추가
---
아직 어드민 인증 관련 기능이 없어서 임시로 파둔 API입니다. 추후 AWS 이전 등 완료된 후 서버 방향성에서 어드민 API를 어디서 관리하는지 결정해야할 것 같습니다
---
https://no5ing.atlassian.net/browse/OING-264

[OING-264] feat: 어드민 대시보드 API

---

family/src/main/java/com/oing/job/FamilyStatisticJob.java
gateway/src/main/java/com/oing/component/SentryGateway.java
gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
gateway/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
gateway/src/main/java/com/oing/job/DailyNotificationJob.java
gateway/src/main/resources/application-dev.yaml
gateway/src/main/resources/application-prod.yaml

---
도입한 Sentry의 로깅 정보가 충분하지 않아, 더 고도화하고 공식 가이드에 맞게 깔끔하게 바꿨습니다.
---
- 정확하지 않아 혼란만 야기시키는 디폴트 로깅 정보 제거
- Requester 정보 로깅 추가
- Serlvet request http 정보 로깅을 가이드에 맞게 변경
- 더 깔끔한 핸들링을 위해 Jwt Token 관련 로깅 위치 변경
- 스케줄러 Sentry 로깅 제거
- Sentry의 최소 로깅 레벨을 INFO에서 WARN으로 변경
---
슬랙에 논의한대로 수정하였슴다!
---
https://no5ing.atlassian.net/browse/OING-252

[OING-252] feature: Sentry 로깅 고도화

---

.github/workflows/build-ecr.yaml

---
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[HOTFIX] chore: SENTRY_AUTH_TOKEN 추가

---

family/src/main/java/com/oing/event/FamilyScoreEventListener.java
gateway/src/test/java/com/oing/event/DatabaseCleaner.java
gateway/src/test/java/com/oing/event/DatabaseCleanerExtension.java
gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java
post/src/main/java/com/oing/domain/MemberPostCommentEntityListener.java
post/src/main/java/com/oing/domain/MemberPostRealEmojiEntityListener.java

---
지난 달 활동에 비해 가족 순위가 높다는 제보를 받았지만, 일부 가족은 점수 정합성이 문제 없고 급하지 않아 보류하던 부분을 해결했습니다.
---
- 가족 점수 로직에 대한 테스트 코드 추가
- 리얼 이모지 생성이 게시글 생성 이벤트를 잘못 부르고 있는 문제 해결
- 이벤트 리스너에 로깅 추가
---
비동기 처리나 테스트 코드 등 추가 개선 PR 날릴 예정입니다
---
https://no5ing.atlassian.net/browse/OING-210

[OING-210] fix: 가족 점수 로직 테스트 코드 추가 및 버그 해결

---

gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java

---
[슬랙](https://bibbi-team.slack.com/archives/C06L42PURL0/p1710027135511869)
---
iOS 딥링크 변경사항을 대응하였습니다.
---
파이팅~
---
https://no5ing.atlassian.net/browse/OING-287

[OING-287] feat: iOS 딥링크 변경사항 대응

---

build.gradle
gateway/src/main/java/com/oing/component/ApplicationListener.java
gateway/src/main/java/com/oing/component/SlackGateway.java
gateway/src/main/java/com/oing/config/properties/ExternalUrlProperties.java
gateway/src/main/java/com/oing/event/ApplicationEventListener.java
gateway/src/main/resources/application.yaml

---
슬랙 알림 채널 분리
---
- 슬랙 알림 분리
- 스프링 부트시 알림 발송
---
ㅎㅇㅌ
---
https://no5ing.atlassian.net/browse/OING-280

[OING-280] feat: 슬랙 알림 분리 및 부팅 알림 추가

---

gateway/src/test/java/com/oing/event/DatabaseCleaner.java

Reverts depromeet/14th-team5-BE#208
---
https://no5ing.atlassian.net/browse/OING-288

revert: Revert "[OING-288] fix: 테스트 중 FamilyScoreEventListnerTest가 실패하는 문제 해결"

---

gateway/src/main/java/com/oing/config/support/RedisLocalConfig.java
gateway/src/main/java/com/oing/job/DailyNotificationJob.java
gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
post/src/main/java/com/oing/controller/MemberPostController.java
post/src/main/java/com/oing/controller/MemberPostReactionController.java
post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java
post/src/main/java/com/oing/service/MemberPostCommentService.java
post/src/main/java/com/oing/service/MemberPostReactionService.java
post/src/main/java/com/oing/service/MemberPostRealEmojiService.java
post/src/main/java/com/oing/service/MemberPostService.java
post/src/test/java/com/oing/controller/MemberPostControllerTest.java
post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java
post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
post/src/test/java/com/oing/service/MemberPostRealEmojiServiceTest.java

---
MemberPost/MemberPostRealEmoji 두가지 로직에서 save 로직 중 안티패턴 코드를 우선적으로 리팩터링했습니다.
---
- MemberPost save 로직 안티패턴 리팩터링
- MemberPostRealEmoji save 로직 안티패턴 리팩터링
---
기존에 존재하던 로직이 알맞게 수정된 건지 확인 부탁드려요~
---
https://no5ing.atlassian.net/browse/OING-219
---
https://no5ing.atlassian.net/browse/OING-219

[OING-219] refactor: MemberPost/MemberPostRealEmoji save 로직 리팩터링

---

family/src/main/java/com/oing/controller/FamilyController.java
family/src/main/java/com/oing/repository/FamilyRepository.java
family/src/main/java/com/oing/service/FamilyService.java

---
전체 모듈 리팩토링 및 안티패턴 개선 주간 중 Family 모듈 리팩토링에 대한 PR입니다. Family 모듈은 따로 안티패턴은 없고, 짜짤한 개선 위주입니다.
---
- 전체적으로 이름과 포멧 리팩토링
- 불필요한 DTO 변환 코드 리팩토링
---
---
https://no5ing.atlassian.net/browse/OING-285

[OING-285] refactor: Family 모듈 리팩토링

---

gateway/src/test/java/com/oing/event/DatabaseCleaner.java

---
Revert #212(revert #202)
---
- FamilyScoreEventListnerTest의 DatabaseCleaner 익스텐션이 flyway db는 truncate하지 않도록 예외 추가
---
큰 변경점없이 픽스한거니 빠르게 부탁드려요!
---

revert: revert #212

---

post/src/main/java/com/oing/controller/CommentController.java
post/src/main/java/com/oing/controller/MemberRealEmojiController.java
post/src/main/java/com/oing/controller/ReactionController.java
post/src/main/java/com/oing/controller/RealEmojiController.java

---
급한 사항이라 일단 Controller에 transactional 붙이고 핫픽스하겠습니다. 이후에 어떻게 대처할지는 회의때 얘기해볼게요.
---
- Post 모듈 안의 N:1 lazily initialize 에러 핫픽스
---
< 여기에 하고싶은 말 >
---
https://no5ing.atlassian.net/browse/OING-297

[OING-297] hotfix: Post 모듈 안의 N:1 lazily initialize 에러 핫픽스

---

common/src/main/java/com/oing/exception/ErrorCode.java

---
화의에서 제안했던 에러 메시지 한글화입니다.
---
- Error message 한글로 번역
---
---
https://no5ing.atlassian.net/browse/OING-298

[OING-298] refactor: Error message 한글로 번역

---

common/src/main/java/com/oing/exception/ErrorCode.java
common/src/main/java/com/oing/service/PostBridge.java
gateway/src/main/resources/db/migration/V202404021150__create_memberPick_table.sql
gateway/src/main/resources/db/migration/V202404031316__add_memberPick_index.sql
member/src/main/java/com/oing/controller/MemberController.java
member/src/main/java/com/oing/domain/MemberPick.java
member/src/main/java/com/oing/exception/AlreadyPickedMemberException.java
member/src/main/java/com/oing/exception/PickFailedAlreadyUploadedException.java
member/src/main/java/com/oing/repository/MemberPickRepository.java
member/src/main/java/com/oing/restapi/MemberApi.java
member/src/main/java/com/oing/service/MemberPickService.java
post/src/main/java/com/oing/service/PostBridgeImpl.java

---
3.0 MVP용 콕 찌르기
---
- 콕 찌르는 API 추가
- 콕 찌른사람 조회 API 추가
- 콕 찔린사람 조회 API 추가
---
ㅎㅇㅌ
---
https://no5ing.atlassian.net/browse/OING-300

[OING-300] feat: 콕 찌르기 API 구현

---

gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
post/src/main/java/com/oing/domain/Post.java

---
Type Enum 필드에 enumerated 추가
---
Type Enum 필드에 enumerated 추가
---
핫픽스라 바로 머지합니다
---
https://no5ing.atlassian.net/browse/OING-306

[OING-306] hotfix: Type Enum 필드에 enumerated 추가

---

gateway/src/main/java/com/oing/controller/ViewBasedController.java
gateway/src/main/java/com/oing/dto/response/MainPageFeedResponse.java
gateway/src/main/java/com/oing/dto/response/MainPagePickerResponse.java
gateway/src/main/java/com/oing/dto/response/MainPageResponse.java
gateway/src/main/java/com/oing/dto/response/MainPageTopBarResponse.java
gateway/src/main/java/com/oing/restapi/ViewBasedApi.java

---
뷰기반 API
---
- 메인 페이지용 Api 개발
---
미션 가능 여부에 true로 박아두었습니다 (아직 구현체가 없는 것 같아)
요 뷰기반 API도 처음 저희 프로젝트에 생기는거다보니 많은 피드백 부탁드립니다~~
cc. @akrudal 요거 머지되고 /v1/view/main API 사용하시면 댑니다
---
https://no5ing.atlassian.net/browse/OING-311

[OING-311] feat: 뷰 기반 API 중 메인 페이지 API 구현

---

gateway/src/main/java/com/oing/controller/MainViewController.java
gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
gateway/src/test/java/com/oing/restapi/PostApiTest.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/dto/response/RemainingSurvivalPostCountResponse.java
post/src/main/java/com/oing/repository/PostRepositoryCustom.java
post/src/main/java/com/oing/restapi/PostApi.java
post/src/main/java/com/oing/service/PostService.java

---
가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 API를 구현했습니다.
---
- 가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 API 구현
- MainViewApi/getDaytimePage에 가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 로직을 연결
- 가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 API에 대해 테스트 코드 작성
---
리뷰 잘부탁합니다~
---
https://no5ing.atlassian.net/browse/OING-316

[OING-316] feature: 가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 API 구현

---

gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/repository/PostRepositoryCustom.java
post/src/main/java/com/oing/service/PostService.java
post/src/test/java/com/oing/service/PostServiceTest.java

---
#239 에 남겨진 코멘트 바탕으로 리팩터링 진행했습니다
---
- #239 에 남겨진 코멘트 바탕으로 리팩터링 진행
- `calculateRemainingSurvivalPostCount` 로직을 두 메서드로 분리
- isActiveMember() 추가
---
리뷰 부탁드립니다~
---
https://no5ing.atlassian.net/browse/OING-320

[OING-320] refactor: 가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 API 로직 리팩터링

---

gateway/src/main/java/com/oing/controller/MainViewController.java
gateway/src/main/java/com/oing/dto/response/DaytimePageResponse.java
gateway/src/main/java/com/oing/dto/response/FamilyMemberMonthlyRankingResponse.java
gateway/src/test/java/com/oing/restapi/PostApiTest.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/dto/response/MissionUploadStatusResponse.java
post/src/main/java/com/oing/dto/response/SurvivalUploadStatusResponse.java
post/src/main/java/com/oing/restapi/PostApi.java

---
요구사항을 구현하기 위해 프론트에서 필요해 요청된 API들입니다.
---
- '지난 날 생존신고 보기' 구현을 위해 getFamilyMemberMonthlyRanking의 FamilyMemberMonthlyRankingResponse에 mostRecentSurvivalPostDate 필드 추가  **((어제 날짜로 응답값을 모킹))**
- DaytimePageResponse에서 isMeUploadedToday -> isMeSurvivalUploadedToday 로 변환하고, isMeMissionUploadedToday을 추가  **((기능구현))**
---
---
https://no5ing.atlassian.net/browse/OING-319

[OING-319] feat: 메인 페이지에서 필요한 추가 요청받은 API 구현/모킹

---

build.gradle
gateway/src/main/java/com/oing/component/SentryGateway.java
gateway/src/main/java/com/oing/controller/CalendarController.java
gateway/src/main/java/com/oing/controller/MainViewController.java
gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java
gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
gateway/src/main/resources/application.yaml
gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
member/src/main/java/com/oing/controller/MemberController.java
post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/repository/PostRepositoryCustom.java
post/src/main/java/com/oing/service/PostService.java

---
변경사항 적용
---
이하 커밋 참조
---
버전 관리 다시 1.2.0으로 (앱과 동일하게) 맞췄습니다

[RELEASE/1.2.1] release v1.2.1

---

gateway/src/main/java/com/oing/config/SpringWebConfig.java
gateway/src/main/java/com/oing/controller/FamilyInviteViewController.java

---
새 웹뷰 CORS 관련 이슈로 핫픽스입니다
---
CORS ORIGIN 추가
외 커밋 참조
---
화이팅

[RELEASE/1.2.3][HOTFIX] Release v1.2.3

---

gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/restapi/MeApi.java

---
내 가족을 조회하고 싶었어요
---
- GET /v1/me/family-info
---
백엔드 PR은 오랜만이네용
---
https://no5ing.atlassian.net/browse/OING-347

[OING-347] feat: 내 가족 조회 API 추가

---

.github/workflows/build-dockerhub.yaml
.github/workflows/build-ecr.yaml
.github/workflows/deploy-argocd.yaml
.github/workflows/dev-cicd.yaml
.github/workflows/prod-cicd.yaml
gateway/src/main/java/com/oing/controller/MeController.java
gateway/src/main/java/com/oing/restapi/MeApi.java

---
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[RELEASE] v1.2.5 릴리즈

---

.github/workflows/prod-cicd.yaml

---
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[RELEASE] 릴리즈 v1.2.5

---

family/src/main/java/com/oing/domain/Family.java

---
가족 이름 변경 API에서 버그?로 추정되는 로직을 수정했습니다
---
- 가족 이름 변경 도메인 로직 수정
---
단순 코드 순서 수정이라 바로 merge하겠습니다
---
https://no5ing.atlassian.net/browse/OING-377

[OING-377] fix: 가족 이름 변경 도메인 로직 수정

---

gateway/src/main/java/com/oing/controller/NotificationController.java
post/src/main/java/com/oing/controller/CommentController.java
post/src/main/java/com/oing/controller/VoiceCommentController.java
post/src/main/java/com/oing/domain/BaseComment.java
post/src/main/java/com/oing/domain/Comment.java
post/src/main/java/com/oing/domain/VoiceComment.java
post/src/main/java/com/oing/dto/response/PostCommentResponseV2.java

---
음성 댓글 기능이 추가되면서 기존 댓글 조회 로직이 복잡해졌습니다. 이에 따라 코드의 가독성과 유지보수성을 높이기 위해 로직을 리팩터링하였습니다.
---
- BaseComment 추가
- 기존 댓글 조회 로직 리팩터링
- 알람 기능 응답 에러 수정
---
추가적으로 더 고려해야 할 부분이 있는지 확인해주세요
---
https://no5ing.atlassian.net/browse/OING-381

[OING-381] refact: Comment, VoiceComment 및 댓글 조회 로직 리팩터링

---

post/src/main/java/com/oing/controller/CommentController.java
post/src/main/java/com/oing/controller/VoiceCommentController.java
post/src/main/java/com/oing/dto/response/PostCommentResponse.java
post/src/test/java/com/oing/controller/PostCommentControllerTest.java

---
프론트의 요청으로 PostCommentResponse에 voiceUrl 필드를 추가했습니다.
---
- PostCommentResponse에 voiceUrl 추가
- 통합 테스트에서 깨지는 테스트 코드 제거
---
< 여기에 하고싶은 말 >
---
https://no5ing.atlassian.net/browse/OING-387

[OING-387] feat: PostCommentResponse에 voiceUrl 추가

---

gateway/src/main/java/com/oing/service/MemberNotificationHistoryService.java

---
- 시스템 멤버가 보낸 알림의 시스템 멤버 프로필이 빈 값이라 시스템 멤버 프로필 이미지가 나오도록 설정했습니다.
---
- 시스템 멤버가 보낸 알림에 시스템 멤버 프로필 이미지 설정
---
개발 서버에서의 테스트를 위해 바로 머지하겠습니다

[OING-388] fix: 시스템 멤버가 보낸 알림에 시스템 멤버 프로필 이미지 설정

---

gateway/src/main/java/com/oing/service/MemberNotificationHistoryService.java
gateway/src/main/resources/db/migration/V202503262043__update_system_member_profile_img.sql

---
시스템 계정 프로필 이미지 수정을 위한 마이그레이션 파일 추가
---
- 시스템 계정 프로필 이미지 수정을 위한 마이그레이션 파일 추가
---
< 여기에 하고싶은 말 >
---
https://no5ing.atlassian.net/browse/OING-389

[OING-389] feat: 시스템 계정 프로필 이미지 수정을 위한 마이그레이션 파일 추가

---

gateway/src/main/java/com/oing/service/MemberNotificationHistoryService.java
gateway/src/main/resources/db/migration/V202503262043__update_system_member_profile_img.sql

---
시스템 알림 프로필 미표시 버그 해결 릴리즈
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[RELEASE] 릴리즈 v1.2.7

---

gateway/src/main/java/com/oing/controller/MainViewController.java
gateway/src/main/java/com/oing/dto/response/DaytimePageResponse.java
gateway/src/main/java/com/oing/dto/response/NighttimePageResponse.java
gateway/src/main/java/com/oing/repository/MemberNotificationHistoryRepository.java
gateway/src/main/java/com/oing/service/MemberNotificationHistoryService.java

---
- 홈 화면 응답에 최신 notification_id 추가 (안 읽은 알림 표시용)
---
- 홈 화면 응답에 최신 notification_id 추가 (안 읽은 알림 표시용)
---
< 여기에 하고싶은 말 >
---
https://no5ing.atlassian.net/browse/OING-390

[OING-390] feature: 홈 화면 응답에 최신 notification_id 추가 (안 읽은 알림 표시용)

---

post/src/main/java/com/oing/controller/PostController.java
post/src/main/java/com/oing/dto/response/AiImageCountResponse.java
post/src/main/java/com/oing/restapi/PostApi.java

---
FE 요청으로 두 기능을 하나로 합쳐요~
---
< 여기에 기능 >
---
바로 머지할게요~!

refactor: `getAiImagePostCount`와 `getRemainingAiImageCount` 기능을 합쳐요.

---

gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java

---
deprecated된 fetchResults()를 fetch + count 방식으로 리팩터링하여 안전한 페이징 처리 적용
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

hotfix: deprecated된 fetchResults()를 대체하여 페이징 조회 로직 개선

---

gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java

---
deprecated된 fetchResults()를 fetch + count 방식으로 리팩터링하여 안전한 페이징 처리 적용한 PR 핫픽스해여
---
< 여기에 기능 >
---
< 여기에 하고싶은 말 >

[RELEASE] 릴리즈 v1.3.2
